/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PersonDirectory;

import Business.Business;
import Business.Person;
import Business.User;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Menita Koonani
 */
public class FindPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FindPersonJPanel
     */
    JPanel UserProcessContainer;
    Business business;

    public FindPersonJPanel(JPanel UserProcessContainer, Business business) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.business = business;
        findTablePanel.setVisible(false);
        firstnamelabel.setVisible(false);
        firstnameField.setVisible(false);
        lastnamelabel.setVisible(false);
        lastnameField.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managePersonDir = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        personId = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        lastnamelabel = new javax.swing.JLabel();
        firstnameField = new javax.swing.JTextField();
        firstnamelabel = new javax.swing.JLabel();
        lastnameField = new javax.swing.JTextField();
        findTablePanel = new javax.swing.JScrollPane();
        findPersonTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        managePersonDir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        managePersonDir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        managePersonDir.setText("Find Person");
        add(managePersonDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 24, 720, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Enter Person ID : ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 200, 30));
        add(personId, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 230, 30));

        searchBtn.setBackground(new java.awt.Color(0, 153, 153));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 120, -1));

        lastnamelabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lastnamelabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastnamelabel.setText("Last Name : ");
        add(lastnamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 30));

        firstnameField.setEditable(false);
        add(firstnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 160, 30));

        firstnamelabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        firstnamelabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstnamelabel.setText("First Name : ");
        add(firstnamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, 30));

        lastnameField.setEditable(false);
        add(lastnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 160, 30));

        findPersonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "User Role", "Account Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        findTablePanel.setViewportView(findPersonTable);

        add(findTablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 410, 260));

        backBtn.setBackground(new java.awt.Color(0, 153, 153));
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        int personID = Integer.parseInt(personId.getText());
        if (personId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter person id to search!", "Warning", JOptionPane.WARNING_MESSAGE);
            personId.requestFocus();
            return;
        }
        Person person = business.getPersonDirectory().getPersonByPersonId(personID);
        if (person == null) {
            JOptionPane.showMessageDialog(null, "Person not found!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        firstnamelabel.setVisible(true);
        firstnameField.setVisible(true);
        lastnamelabel.setVisible(true);
        lastnameField.setVisible(true);
        firstnameField.setText(person.getFirstName());
        lastnameField.setText(person.getLastName());

        if (!person.getUserList().isEmpty()) {
            findTablePanel.setVisible(true);
            DefaultTableModel findPersonTbl = (DefaultTableModel) findPersonTable.getModel();
            findPersonTbl.setRowCount(0);
            for (User eachUser : person.getUserList()) {
                Object row[] = new Object[4];
                row[0] = eachUser.getUsername();
                row[1] = eachUser.getUserPassword();
                row[2] = eachUser.getUserRole();
                row[3] = eachUser.isActive();
                findPersonTbl.addRow(row);
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        Component[] componentArray = UserProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManagePersonDirectory managePersonDir = (ManagePersonDirectory) component;
        managePersonDir.populateManagePersonPanel();
        CardLayout cardLayout = (CardLayout) UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable findPersonTable;
    private javax.swing.JScrollPane findTablePanel;
    private javax.swing.JTextField firstnameField;
    private javax.swing.JLabel firstnamelabel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JLabel lastnamelabel;
    private javax.swing.JLabel managePersonDir;
    private javax.swing.JTextField personId;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
}
