/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PersonDirectory;

import UserInterface.UserDirectory.ManageUserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Menita Koonani
 */
public class PersonWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserWorkAreaJPanel
     */
    JPanel UserProcessContainer;

    public PersonWorkAreaJPanel(JPanel UserProcessContainer) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        roleField = new javax.swing.JLabel();
        UserIDField = new javax.swing.JLabel();
        NameField = new javax.swing.JLabel();
        workAreaPanelHeader = new javax.swing.JLabel();
        manageUsersBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Role : ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("User ID : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Name : ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 200, 30));

        roleField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(roleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 200, 30));

        UserIDField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(UserIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 200, 30));

        NameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 200, 30));

        workAreaPanelHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        workAreaPanelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        workAreaPanelHeader.setText("Person Work Area Panel");
        add(workAreaPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 24, 760, 60));

        manageUsersBtn.setBackground(new java.awt.Color(0, 153, 153));
        manageUsersBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageUsersBtn.setText("Manage Person Directory");
        manageUsersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsersBtnActionPerformed(evt);
            }
        });
        add(manageUsersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 243, 230, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void manageUsersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsersBtnActionPerformed
        // TODO add your handling code here:
        ManageUserAccountDirectory manageUserAccDir = new ManageUserAccountDirectory(UserProcessContainer);
        CardLayout cardLayout = (CardLayout) UserProcessContainer.getLayout();
        UserProcessContainer.add("ManageUserAccDirPanel", manageUserAccDir);
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_manageUsersBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameField;
    private javax.swing.JLabel UserIDField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton manageUsersBtn;
    private javax.swing.JLabel roleField;
    private javax.swing.JLabel workAreaPanelHeader;
    // End of variables declaration//GEN-END:variables
}
