/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PersonDirectory;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Menita Koonani
 */
public class UpdatePersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdatePersonJPanel
     */
    JPanel UserProcessContainer;
    public UpdatePersonJPanel(JPanel UserProcessContainer) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newPersonHeader = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        lastnameField = new javax.swing.JTextField();
        updatePersonBtn = new javax.swing.JButton();
        cancelPersonBtn = new javax.swing.JButton();
        firstnameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newPersonHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newPersonHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newPersonHeader.setText("Update Person");
        add(newPersonHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 24, 760, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Password : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("First name : ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Last name : ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Username : ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 200, 30));

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 230, 30));
        add(lastnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 230, 30));

        updatePersonBtn.setBackground(new java.awt.Color(0, 153, 153));
        updatePersonBtn.setText("Update");
        add(updatePersonBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 120, 30));

        cancelPersonBtn.setBackground(new java.awt.Color(0, 153, 153));
        cancelPersonBtn.setText("<< Cancel");
        cancelPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPersonBtnActionPerformed(evt);
            }
        });
        add(cancelPersonBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 110, 30));
        add(firstnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 230, 30));
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 230, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void cancelPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPersonBtnActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        Component[] componentArray = UserProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManagePersonDirectory managePersonDir = (ManagePersonDirectory) component;
        managePersonDir.populateManagePersonDir();
        CardLayout cardLayout = (CardLayout) UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_cancelPersonBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelPersonBtn;
    private javax.swing.JTextField firstnameField;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JLabel newPersonHeader;
    private javax.swing.JTextField passwordField;
    private javax.swing.JButton updatePersonBtn;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
