/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Airplane.Airplane;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Menita Koonani
 */
public class AirplaneManufactureList extends javax.swing.JPanel {

    /**
     * Creates new form airplaneManufactureList
     */
    public AirplaneManufactureList() {
        initComponents();
        manuListPanelHeader.setVisible(false);
        manuTable.setVisible(false);
    }

    public void populateManufactureTable(String airlinerName) {
        if (MainJFrame.airplaneCatalog.isAirlinerInCatalog(airlinerName)) {
            manuTable.setVisible(true);
            manuListPanelHeader.setVisible(true);
            manuListPanelHeader.setText("Manufacturers of " + airlinerName);
            ArrayList<Airplane> airplaneList = MainJFrame.airplaneCatalog.getAirplaneByName(airlinerName);
            DefaultTableModel airplaneTable = (DefaultTableModel) manuTable.getModel();
            airplaneTable.setNumRows(0);
            //starting the population form row 0
            airplaneTable.setRowCount(0);
            for (Airplane eachAirplane : airplaneList) {
                Object row[] = new Object[3];
                //setting the object to the first row as we need to access all the other attributes of that particular object
                row[0] = eachAirplane;
                row[1] = eachAirplane.getAirplaneName();
                row[2] = eachAirplane.getManufacturerName();
                airplaneTable.addRow(row);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter the full airliner's name!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        manuTable = new javax.swing.JTable();
        manuListPanelHeader = new javax.swing.JLabel();
        airplaneNameSearchLabel = new javax.swing.JLabel();
        airplaneNameSearchField = new javax.swing.JTextField();
        searchManuBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airplane Serial Number", "Airplane Name", "Manufacturer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manuTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 157, 441, 289));

        manuListPanelHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        manuListPanelHeader.setText("Airliner - Manufacturer Details");
        add(manuListPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 102, -1, -1));

        airplaneNameSearchLabel.setText("Enter airliner name to search:");
        add(airplaneNameSearchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 40, -1, -1));
        add(airplaneNameSearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 37, 148, -1));

        searchManuBtn.setText("Search");
        searchManuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchManuBtnActionPerformed(evt);
            }
        });
        add(searchManuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 68, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void searchManuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchManuBtnActionPerformed
        // TODO add your handling code here:
        populateManufactureTable(airplaneNameSearchField.getText());
    }//GEN-LAST:event_searchManuBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airplaneNameSearchField;
    private javax.swing.JLabel airplaneNameSearchLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manuListPanelHeader;
    private javax.swing.JTable manuTable;
    private javax.swing.JButton searchManuBtn;
    // End of variables declaration//GEN-END:variables
}
