/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Menita Koonani
 */
public class LastTimeFleetUpdated extends javax.swing.JPanel {

    /**
     * Creates new form LastTimeFleetUpdated
     */
    public LastTimeFleetUpdated() {
        initComponents();
        fleetUpdateField.setEditable(false);
        fleetUpdateField.setText(MainJFrame.airplaneCatalog.getLastFleetUpdatedTime()!=null?MainJFrame.airplaneCatalog.getLastFleetUpdatedTime():"Empty airplane catalog!!");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fleetUpdateLabel = new javax.swing.JLabel();
        fleetUpdateField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fleetUpdateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fleetUpdateLabel.setText("The last time fleet was updated : ");
        add(fleetUpdateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 74, -1, -1));
        add(fleetUpdateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 74, 247, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fleetUpdateField;
    private javax.swing.JLabel fleetUpdateLabel;
    // End of variables declaration//GEN-END:variables
}
