/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Airplane.Airplane;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Menita Koonani
 */
public class ViewAllAirplaneJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAllAirplaneJPanel
     */
    public ViewAllAirplaneJPanel() {
        initComponents();
        updateChangesBtn.setVisible(false);
        viewAllAirplaneDetails();
    }

    public void viewAllAirplaneDetails() {
        ArrayList<Airplane> airplaneList = MainJFrame.airplaneCatalog.getAirplanesList();
        if (airplaneList != null) {
            populateTable(airplaneList);
            airplaneCountField.setText(String.valueOf(airplaneList.size()));
        } else {
            JOptionPane.showMessageDialog(null, "The airplane catalog is empty!");
        }
    }

    public void populateTable(ArrayList<Airplane> airplaneList) {
        DefaultTableModel airplaneTable = (DefaultTableModel) viewAirplaneTable.getModel();
        airplaneTable.setNumRows(0);
        //starting the population form row 0
        airplaneTable.setRowCount(0);
        for (Airplane eachAirplane : airplaneList) {
            Object row[] = new Object[6];
            //setting the object to the first row as we need to access all the other attributes of that particular object
            row[0] = eachAirplane;
            row[1] = eachAirplane.getAirlinerName();
            row[2] = eachAirplane.getAirplaneName();
            row[3] = eachAirplane.getAirportName();
            row[4] = eachAirplane.getSeatsAvailable();
            row[5] = eachAirplane.isAvailable();
            airplaneTable.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        availBtnGroup = new javax.swing.ButtonGroup();
        expiryBtnGroup = new javax.swing.ButtonGroup();
        searchPanelHeader = new javax.swing.JLabel();
        viewScrollPane = new javax.swing.JScrollPane();
        viewAirplaneTable = new javax.swing.JTable();
        viewDetailsBtn = new javax.swing.JButton();
        airplaneCountLabel = new javax.swing.JLabel();
        airplaneCountField = new javax.swing.JTextField();
        serialNumberLabel = new javax.swing.JLabel();
        serailNumberField = new javax.swing.JTextField();
        modelNumberLabel = new javax.swing.JLabel();
        modelNumberField = new javax.swing.JTextField();
        airplaneNameLabel = new javax.swing.JLabel();
        airplaneNameField = new javax.swing.JTextField();
        airplaneAvailableLabel = new javax.swing.JLabel();
        manufacturerNameLabel = new javax.swing.JLabel();
        manufacturerNameField = new javax.swing.JTextField();
        yearManuLabel = new javax.swing.JLabel();
        seatsAvailLabel = new javax.swing.JLabel();
        airportNameLabel = new javax.swing.JLabel();
        airportNameField = new javax.swing.JTextField();
        updateAirplaneBtn = new javax.swing.JButton();
        planeAvailable = new javax.swing.JCheckBox();
        planeUnavailable = new javax.swing.JCheckBox();
        yearManuChooser = new com.toedter.calendar.JYearChooser();
        seatsAvailChooser = new com.toedter.components.JSpinField();
        updateChangesBtn = new javax.swing.JButton();
        airplaneAvailableLabel1 = new javax.swing.JLabel();
        invalidCertificate = new javax.swing.JRadioButton();
        validCertificate = new javax.swing.JRadioButton();
        nextAvailFlightLabel = new javax.swing.JLabel();
        nextAvailFlightChooser = new com.toedter.calendar.JDateChooser();
        airlinerNameLabel = new javax.swing.JLabel();
        airlinerNameField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchPanelHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        searchPanelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchPanelHeader.setText("Airplane Details");
        searchPanelHeader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(searchPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 610, -1));

        viewAirplaneTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airplane Serial Number", "Airliner Name", "Airplane Name", "Airport Name", "Seats available", "Is it available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        viewScrollPane.setViewportView(viewAirplaneTable);

        add(viewScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 90, 730, 140));

        viewDetailsBtn.setText("View Details");
        viewDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsBtnActionPerformed(evt);
            }
        });
        add(viewDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        airplaneCountLabel.setText("Number of Airplanes found: ");
        add(airplaneCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 160, 20));

        airplaneCountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airplaneCountFieldActionPerformed(evt);
            }
        });
        add(airplaneCountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 55, -1));

        serialNumberLabel.setText("Airplane Serial  Number:");
        add(serialNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        serailNumberField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(serailNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 143, -1));

        modelNumberLabel.setText("Airplane Model Number:");
        add(modelNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));
        add(modelNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 143, -1));

        airplaneNameLabel.setText("Airplane Name:");
        add(airplaneNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));
        add(airplaneNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 143, -1));

        airplaneAvailableLabel.setText("Is the airplane available:");
        add(airplaneAvailableLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, -1, -1));

        manufacturerNameLabel.setText("Airplane manufacturer name:");
        add(manufacturerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        manufacturerNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturerNameFieldActionPerformed(evt);
            }
        });
        add(manufacturerNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 143, -1));

        yearManuLabel.setText("Year of manufacture:");
        add(yearManuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        seatsAvailLabel.setText("Number of seats available:");
        add(seatsAvailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        airportNameLabel.setText("Airport Name:");
        add(airportNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));
        add(airportNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 143, -1));

        updateAirplaneBtn.setText("Update");
        updateAirplaneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAirplaneBtnActionPerformed(evt);
            }
        });
        add(updateAirplaneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 101, -1));

        availBtnGroup.add(planeAvailable);
        planeAvailable.setSelected(true);
        planeAvailable.setText("Yes");
        planeAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planeAvailableActionPerformed(evt);
            }
        });
        add(planeAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));

        availBtnGroup.add(planeUnavailable);
        planeUnavailable.setText("No");
        add(planeUnavailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, -1, -1));

        yearManuChooser.setEndYear(2017);
        yearManuChooser.setMinimum(1990);
        yearManuChooser.setName("yearOfManu"); // NOI18N
        add(yearManuChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 67, -1));

        seatsAvailChooser.setMaximum(550);
        seatsAvailChooser.setMinimum(0);
        seatsAvailChooser.setName("seatsAvailable"); // NOI18N
        seatsAvailChooser.setValue(550);
        add(seatsAvailChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 67, -1));

        updateChangesBtn.setText("Update changes");
        updateChangesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateChangesBtnActionPerformed(evt);
            }
        });
        add(updateChangesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, -1, -1));

        airplaneAvailableLabel1.setText("Certificate expired:");
        add(airplaneAvailableLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));

        expiryBtnGroup.add(invalidCertificate);
        invalidCertificate.setText("Yes");
        add(invalidCertificate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, -1));

        expiryBtnGroup.add(validCertificate);
        validCertificate.setSelected(true);
        validCertificate.setText("No");
        validCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validCertificateActionPerformed(evt);
            }
        });
        add(validCertificate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, -1, -1));

        nextAvailFlightLabel.setText("Next available Date:");
        add(nextAvailFlightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, -1, -1));
        add(nextAvailFlightChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 160, -1));

        airlinerNameLabel.setText("Airliner Name:");
        add(airlinerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));
        add(airlinerNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 143, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsBtnActionPerformed
        // TODO add your handling code here
        updateChangesBtn.setVisible(false);
        fillIntoFields();
        isEditable(false);
    }//GEN-LAST:event_viewDetailsBtnActionPerformed
    public void fillIntoFields() {
        int selectedRow = viewAirplaneTable.getSelectedRow();
//        selectedRow = selectedRow >= 0 ? selectedRow : (searchAirplaneTable.getRowCount() == 1 ? 0 : -1);
        if (selectedRow >= 0) {
            Airplane airplane = (Airplane) viewAirplaneTable.getValueAt(selectedRow, 0);
            serailNumberField.setText(String.valueOf(airplane.getSerialNumber()));
            modelNumberField.setText(String.valueOf(airplane.getModelNumber()));
            airlinerNameField.setText(String.valueOf(airplane.getAirlinerName()));
            airplaneNameField.setText(String.valueOf(airplane.getAirplaneName()));
            if (airplane.isAvailable()) {
                planeAvailable.setSelected(true);
            } else {
                planeUnavailable.setSelected(true);
            }
            manufacturerNameField.setText(String.valueOf(airplane.getManufacturerName()));
            yearManuChooser.setYear(airplane.getYearOfManufacture());
            seatsAvailChooser.setValue(airplane.getSeatsAvailable());
            airportNameField.setText(String.valueOf(airplane.getAirportName()));
            validCertificate.setSelected(airplane.isCertitficateValid());
            invalidCertificate.setSelected(!airplane.isCertitficateValid());
            nextAvailFlightChooser.setDate(airplane.getNextAvailableDate());

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!!");
        }
    }

    public void isEditable(boolean isEditable) {
        serailNumberField.setEditable(isEditable);
        modelNumberField.setEditable(isEditable);
        airplaneNameField.setEditable(isEditable);
        serailNumberField.setEditable(isEditable);
        airportNameField.setEditable(isEditable);
        airlinerNameField.setEditable(isEditable);
        manufacturerNameField.setEditable(isEditable);

        planeAvailable.setEnabled(isEditable);
        planeUnavailable.setEnabled(isEditable);
        yearManuChooser.setEnabled(isEditable);
        seatsAvailChooser.setEnabled(isEditable);
        validCertificate.setEnabled(isEditable);
        invalidCertificate.setEnabled(isEditable);
        nextAvailFlightChooser.setEnabled(isEditable);
    }

    private void airplaneCountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airplaneCountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airplaneCountFieldActionPerformed

    private void updateAirplaneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAirplaneBtnActionPerformed
        // TODO add your handling code here:
        updateChangesBtn.setVisible(true);
        fillIntoFields();
        isEditable(true);
    }//GEN-LAST:event_updateAirplaneBtnActionPerformed

    private void updateChangesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateChangesBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = viewAirplaneTable.getSelectedRow();
        if (selectedRow >= 0) {
            Airplane airplane = (Airplane) viewAirplaneTable.getValueAt(selectedRow, 0);
            getViewFieldsFromPanel(airplane);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!!");
        }
    }//GEN-LAST:event_updateChangesBtnActionPerformed

    private void manufacturerNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturerNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturerNameFieldActionPerformed

    private void planeAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planeAvailableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planeAvailableActionPerformed

    private void validCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validCertificateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validCertificateActionPerformed

    public void getViewFieldsFromPanel(Airplane airplane) {
        try {
            airplane.setSerialNumber(Long.parseLong(serailNumberField.getText()));
            airplane.setModelNumber(modelNumberField.getText());
            airplane.setAirlinerName(airlinerNameField.getText());
            airplane.setAirplaneName(airplaneNameField.getText());
            airplane.setIsAvailable(planeAvailable.isSelected());
            airplane.setManufacturerName(manufacturerNameField.getText());
            airplane.setYearOfManufacture(yearManuChooser.getYear());
            airplane.setSeatsAvailable(seatsAvailChooser.getValue());
            airplane.setAirportName(airportNameField.getText());
            airplane.setIsCertificateValid(validCertificate.isSelected());
            airplane.setNextAvailableDate(nextAvailFlightChooser.getDate());

            JOptionPane.showMessageDialog(null, "Updated!!");
            resetViewFields();
            isEditable(false);
            populateTable();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Serial Number : Serial Number field can contian only numbers!! Please try again!");
            serailNumberField.requestFocus();
        }
    }

    public void populateTable() {
        ArrayList<Airplane> airplaneList = MainJFrame.airplaneCatalog.getAirplanesList();
        DefaultTableModel airplaneTable = (DefaultTableModel) viewAirplaneTable.getModel();
        airplaneTable.setNumRows(0);
        //starting the population form row 0
        airplaneTable.setRowCount(0);
        for (Airplane eachAirplane : airplaneList) {
            Object row[] = new Object[3];
            //setting the object to the first row as we need to access all the other attributes of that particular object
            row[0] = eachAirplane;
            row[1] = eachAirplane.getAirplaneName();
            row[2] = eachAirplane.getSeatsAvailable();
            airplaneTable.addRow(row);
        }

    }

    public void resetViewFields() {
        serailNumberField.setText("");
        modelNumberField.setText("");
        airplaneNameField.setText("");
        planeAvailable.setSelected(true);
        manufacturerNameField.setText("");
        yearManuChooser.setYear(2017);
        seatsAvailChooser.setValue(550);
        airportNameField.setText("");
        airlinerNameField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlinerNameField;
    private javax.swing.JLabel airlinerNameLabel;
    private javax.swing.JLabel airplaneAvailableLabel;
    private javax.swing.JLabel airplaneAvailableLabel1;
    private javax.swing.JTextField airplaneCountField;
    private javax.swing.JLabel airplaneCountLabel;
    private javax.swing.JTextField airplaneNameField;
    private javax.swing.JLabel airplaneNameLabel;
    private javax.swing.JTextField airportNameField;
    private javax.swing.JLabel airportNameLabel;
    private javax.swing.ButtonGroup availBtnGroup;
    private javax.swing.ButtonGroup expiryBtnGroup;
    private javax.swing.JRadioButton invalidCertificate;
    private javax.swing.JTextField manufacturerNameField;
    private javax.swing.JLabel manufacturerNameLabel;
    private javax.swing.JTextField modelNumberField;
    private javax.swing.JLabel modelNumberLabel;
    private com.toedter.calendar.JDateChooser nextAvailFlightChooser;
    private javax.swing.JLabel nextAvailFlightLabel;
    private javax.swing.JCheckBox planeAvailable;
    private javax.swing.JCheckBox planeUnavailable;
    private javax.swing.JLabel searchPanelHeader;
    private com.toedter.components.JSpinField seatsAvailChooser;
    private javax.swing.JLabel seatsAvailLabel;
    private javax.swing.JTextField serailNumberField;
    private javax.swing.JLabel serialNumberLabel;
    private javax.swing.JButton updateAirplaneBtn;
    private javax.swing.JButton updateChangesBtn;
    private javax.swing.JRadioButton validCertificate;
    private javax.swing.JTable viewAirplaneTable;
    private javax.swing.JButton viewDetailsBtn;
    private javax.swing.JScrollPane viewScrollPane;
    private com.toedter.calendar.JYearChooser yearManuChooser;
    private javax.swing.JLabel yearManuLabel;
    // End of variables declaration//GEN-END:variables
}
