/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Airliner;
import Business.TravelAgency;
import UserInterface.ManageFlights.ManageFlightsJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Menita Koonani
 */
public class ManageAirlinersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinersJPanel
     */
    public TravelAgency travelAgency;
    public javax.swing.JPanel CardSequenceJPanel;

    public ManageAirlinersJPanel(javax.swing.JPanel sequencePanel, TravelAgency travelAgency) {
        initComponents();
        this.CardSequenceJPanel = sequencePanel;
        this.travelAgency = travelAgency;
        populateManageAirlinerTable();
    }

    public void populateManageAirlinerTable() {
        DefaultTableModel jTable = (DefaultTableModel) manageAirlinerTable.getModel();
        //starting the population form row 0
        jTable.setRowCount(0);

//        if (!airlinerDirectory.getAirlinerList().isEmpty()) {
        for (Airliner eachAirliner : travelAgency.getAirlinerDirectory().getAirlinerList()) {
            Object row[] = new Object[4];
            //setting the object to the first row as we need to access all the other attributes of that particular object
            row[0] = eachAirliner;
            row[1] = eachAirliner.getAirlinerName();
            row[2] = eachAirliner.getAirlinerAddress();
            row[3] = eachAirliner.getFlightCount();
            jTable.addRow(row);
        }
//        } else {
//            JOptionPane.showMessageDialog(null, "Airliner Directory is Empty!! ", "Warning", JOptionPane.WARNING_MESSAGE);
//        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageAirlinersLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageAirlinerTable = new javax.swing.JTable();
        newAirlinerBtn = new javax.swing.JButton();
        viewAirlinerBtn = new javax.swing.JButton();
        manageFlightsBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageAirlinersLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageAirlinersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageAirlinersLabel.setText("Manage Airliners");
        add(manageAirlinersLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 750, 30));

        manageAirlinerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Id", "Airliner Name", "Airliner Address", "Number of Flights"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageAirlinerTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 750, 230));

        newAirlinerBtn.setBackground(new java.awt.Color(0, 153, 153));
        newAirlinerBtn.setText("New Airliner >>");
        newAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAirlinerBtnActionPerformed(evt);
            }
        });
        add(newAirlinerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 150, 30));

        viewAirlinerBtn.setBackground(new java.awt.Color(0, 153, 153));
        viewAirlinerBtn.setText("View Airliner >>");
        viewAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAirlinerBtnActionPerformed(evt);
            }
        });
        add(viewAirlinerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 150, 30));

        manageFlightsBtn.setBackground(new java.awt.Color(0, 153, 153));
        manageFlightsBtn.setText("Manage Flights");
        manageFlightsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFlightsBtnActionPerformed(evt);
            }
        });
        add(manageFlightsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void newAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAirlinerBtnActionPerformed
        // TODO add your handling code here:
        CreateNewAirlinerJPanel newAirlinerPanel = new CreateNewAirlinerJPanel(CardSequenceJPanel, travelAgency.getAirlinerDirectory());
        CardLayout cardLayout = (CardLayout) CardSequenceJPanel.getLayout();
        CardSequenceJPanel.add("NewAirlinerPanel", newAirlinerPanel);
        cardLayout.next(CardSequenceJPanel);
    }//GEN-LAST:event_newAirlinerBtnActionPerformed

    private void viewAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAirlinerBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = manageAirlinerTable.getSelectedRow();
        if (selectedRow >= 0) {
            Airliner selectedAirliner = (Airliner) manageAirlinerTable.getValueAt(selectedRow, 0);
            ViewAirlinerJPanel viewAirlinerPanel = new ViewAirlinerJPanel(CardSequenceJPanel, selectedAirliner, travelAgency.getAirlinerDirectory());
            CardLayout cardLayout = (CardLayout) CardSequenceJPanel.getLayout();
            CardSequenceJPanel.add("ViewAirlinerPanel", viewAirlinerPanel);
            cardLayout.next(CardSequenceJPanel);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row! ", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_viewAirlinerBtnActionPerformed

    private void manageFlightsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFlightsBtnActionPerformed
        // TODO add your handling code here:
        ManageFlightsJPanel manageFlightPanel = new ManageFlightsJPanel(CardSequenceJPanel, travelAgency.getAirlinerDirectory());
        CardLayout cardLayout = (CardLayout) CardSequenceJPanel.getLayout();
        CardSequenceJPanel.add("ManageFlightPanel", manageFlightPanel);
        cardLayout.next(CardSequenceJPanel);
    }//GEN-LAST:event_manageFlightsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable manageAirlinerTable;
    private javax.swing.JLabel manageAirlinersLabel;
    private javax.swing.JButton manageFlightsBtn;
    private javax.swing.JButton newAirlinerBtn;
    private javax.swing.JButton viewAirlinerBtn;
    // End of variables declaration//GEN-END:variables
}
