/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Menita Koonani
 */
public class AccountMgmWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserInterfacePanel
     */
    private JPanel userProcessContainer;
    private AccountDirectory accountDirectory;
    AccountMgmWorkAreaPanel(JPanel userProcessContainer, AccountDirectory accountDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.accountDirectory = accountDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAccBtn = new javax.swing.JButton();
        manageAccBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createAccBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createAccBtn.setText("Create Account");
        createAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccBtnActionPerformed(evt);
            }
        });
        add(createAccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 109, 313, 66));

        manageAccBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageAccBtn.setText("Manage Account");
        manageAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccBtnActionPerformed(evt);
            }
        });
        add(manageAccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 210, 313, 66));
    }// </editor-fold>//GEN-END:initComponents

    private void createAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccBtnActionPerformed
        // TODO add your handling code here:
        CreateAccountPanel createPanel = new CreateAccountPanel(userProcessContainer,accountDirectory);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("CreatePanel",createPanel);
        cardLayout.next(userProcessContainer);
        
    }//GEN-LAST:event_createAccBtnActionPerformed

    private void manageAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAccBtnActionPerformed
        // TODO add your handling code here:
        ManageAccountPanel managePanel = new ManageAccountPanel(userProcessContainer,accountDirectory);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManagePanel",managePanel);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_manageAccBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAccBtn;
    private javax.swing.JButton manageAccBtn;
    // End of variables declaration//GEN-END:variables
}
