/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Account;
import Business.AccountDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Menita Koonani
 */
public class CreateAccountPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAccountPanel
     */
    private JPanel userProcessPanel;
    private AccountDirectory accountDirectory;

    CreateAccountPanel(JPanel userProcessPanel, AccountDirectory accountDirectory) {
        initComponents();
        this.userProcessPanel = userProcessPanel;
        this.accountDirectory = accountDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAccLabel = new javax.swing.JLabel();
        accNumLabel = new javax.swing.JLabel();
        bankNameLabel = new javax.swing.JLabel();
        accRoutingLabel = new javax.swing.JLabel();
        accNumField = new javax.swing.JTextField();
        accRoutingField = new javax.swing.JTextField();
        bankNameField = new javax.swing.JTextField();
        createAccountBtn = new javax.swing.JButton();
        balanceLabel = new javax.swing.JLabel();
        balanceField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createAccLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        createAccLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createAccLabel.setText("Create Account");
        add(createAccLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 53, 745, 50));

        accNumLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        accNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        accNumLabel.setText("Account Number : ");
        add(accNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 234, 160, 29));

        bankNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bankNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bankNameLabel.setText("Bank Name : ");
        add(bankNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 282, 160, 29));

        accRoutingLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        accRoutingLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        accRoutingLabel.setText("Account Routing Number : ");
        add(accRoutingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 186, 160, 29));
        add(accNumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 235, 182, 29));
        add(accRoutingField, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 187, 182, 29));
        add(bankNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 283, 182, 29));

        createAccountBtn.setText("Create");
        createAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountBtnActionPerformed(evt);
            }
        });
        add(createAccountBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 404, 105, 33));

        balanceLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        balanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        balanceLabel.setText("Balance : ");
        add(balanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 330, 160, 29));
        add(balanceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 331, 182, 29));

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 140, 92, 35));
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountBtnActionPerformed
        // TODO add your handling code here:
        try {
            String routingNum = accRoutingField.getText();
            String bankNum = bankNameField.getText();
            Integer accNum = Integer.parseInt(accNumField.getText());
            Integer balance = Integer.parseInt(balanceField.getText());

            if (!routingNum.isEmpty() && !bankNum.isEmpty() && balanceField != null && accNumField != null) {
                Account account = accountDirectory.addNewAccount();
                account.setAccountNumber(accNum);
                account.setRoutingNumber(routingNum);
                account.setBalance(balance);
                account.setBankName(bankNum);
                account.setCreatedOn(new Date(System.currentTimeMillis()));
                JOptionPane.showMessageDialog(null, "Account added successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "All fields are mandatory!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Enter only numbers in balance field!", "Warning", JOptionPane.WARNING_MESSAGE);
            balanceField.requestFocus();
        }
    }//GEN-LAST:event_createAccountBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessPanel.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessPanel.getLayout();
        cardLayout.previous(userProcessPanel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accNumField;
    private javax.swing.JLabel accNumLabel;
    private javax.swing.JTextField accRoutingField;
    private javax.swing.JLabel accRoutingLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField balanceField;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JTextField bankNameField;
    private javax.swing.JLabel bankNameLabel;
    private javax.swing.JLabel createAccLabel;
    private javax.swing.JButton createAccountBtn;
    // End of variables declaration//GEN-END:variables
}
