/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Enterprise.HospitalEnterprise;
import Business.Organization.DoctorOrganization;
import Business.UserAccount.UserAccount;
import UserInterface.DoctorRole.RequestVaccineJPanel;
import UserInterface.DoctorRole.ManageVaccineRequestsJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Menita Koonani
 */
public class DoctorsWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private HospitalEnterprise enterprise;
    private UserAccount account;
    private DoctorOrganization organization;

    /**
     * Creates new form DoctorsWorkAreaJPanel
     */
    public DoctorsWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization organization, HospitalEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.organization = organization;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        manageDiseasesBtn = new javax.swing.JButton();
        manageVaccinesBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 127, 30));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 158, 26));

        manageDiseasesBtn.setText("Manage Diseases");
        manageDiseasesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDiseasesBtnActionPerformed(evt);
            }
        });
        add(manageDiseasesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 180, -1));

        manageVaccinesBtn.setText("Manage Vaccine Requests");
        manageVaccinesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVaccinesBtnActionPerformed(evt);
            }
        });
        add(manageVaccinesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageDiseasesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDiseasesBtnActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageDiseasesJPanel", new ManageDiseasesJPanel(userProcessContainer, enterprise));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageDiseasesBtnActionPerformed

    private void manageVaccinesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVaccinesBtnActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageVaccineRequestsJPanel", new ManageVaccineRequestsJPanel(userProcessContainer, account, organization, enterprise));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageVaccinesBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton manageDiseasesBtn;
    private javax.swing.JButton manageVaccinesBtn;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
