/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import UserApplication.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Menita Koonani
 */
public class CreateCreditCardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateCreditCardJPanel
     */
    private CreditCard creditCard;
    public CreateCreditCardJPanel(Person person) {
        initComponents();
        this.creditCard = new CreditCard();
        person.setCreditCard(this.creditCard);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createCreditJPanel = new javax.swing.JPanel();
        addCreditCardLabel = new javax.swing.JLabel();
        creditCardNumLabel = new javax.swing.JLabel();
        creditCardHolderLabel = new javax.swing.JLabel();
        creditCardExpiryLabel = new javax.swing.JLabel();
        creditCardIssueLabel = new javax.swing.JLabel();
        creditCardCvvLabel = new javax.swing.JLabel();
        cardHolderNameTextField = new javax.swing.JTextField();
        cardNumTextField = new javax.swing.JTextField();
        cardCvvTextField = new javax.swing.JTextField();
        cardIssueTextField = new javax.swing.JTextField();
        cardExpiryTextField = new javax.swing.JTextField();
        addCreditCardBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        addCreditCardLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addCreditCardLabel.setText("Add your Credit Card Details");

        creditCardNumLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditCardNumLabel.setText("Enter credit card number:");

        creditCardHolderLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditCardHolderLabel.setText("Enter card holder name:");

        creditCardExpiryLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditCardExpiryLabel.setText("Enter credit card expiry date:");

        creditCardIssueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditCardIssueLabel.setText("Enter credit card issue date:");

        creditCardCvvLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditCardCvvLabel.setText("Enter credit card CVV number:");

        cardCvvTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardCvvTextFieldActionPerformed(evt);
            }
        });

        cardIssueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardIssueTextFieldActionPerformed(evt);
            }
        });

        cardExpiryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardExpiryTextFieldActionPerformed(evt);
            }
        });

        addCreditCardBtn.setText("Add card details");
        addCreditCardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCreditCardBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createCreditJPanelLayout = new javax.swing.GroupLayout(createCreditJPanel);
        createCreditJPanel.setLayout(createCreditJPanelLayout);
        createCreditJPanelLayout.setHorizontalGroup(
            createCreditJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCreditJPanelLayout.createSequentialGroup()
                .addGroup(createCreditJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createCreditJPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(addCreditCardLabel))
                    .addGroup(createCreditJPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(createCreditJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(creditCardHolderLabel)
                            .addComponent(creditCardNumLabel)
                            .addComponent(creditCardExpiryLabel)
                            .addComponent(creditCardIssueLabel)
                            .addComponent(creditCardCvvLabel))
                        .addGap(43, 43, 43)
                        .addGroup(createCreditJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cardHolderNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardCvvTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardIssueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardExpiryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createCreditJPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addCreditCardBtn)
                .addGap(176, 176, 176))
        );
        createCreditJPanelLayout.setVerticalGroup(
            createCreditJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCreditJPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(addCreditCardLabel)
                .addGap(26, 26, 26)
                .addGroup(createCreditJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditCardNumLabel)
                    .addComponent(cardNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createCreditJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditCardHolderLabel)
                    .addComponent(cardHolderNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(createCreditJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditCardCvvLabel)
                    .addComponent(cardCvvTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createCreditJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditCardIssueLabel)
                    .addComponent(cardIssueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createCreditJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditCardExpiryLabel)
                    .addComponent(cardExpiryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(addCreditCardBtn)
                .addContainerGap())
        );

        add(createCreditJPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cardCvvTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardCvvTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardCvvTextFieldActionPerformed

    private void cardIssueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardIssueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardIssueTextFieldActionPerformed

    private void cardExpiryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardExpiryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardExpiryTextFieldActionPerformed

    private void addCreditCardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCreditCardBtnActionPerformed
        // TODO add your handling code here:
        creditCard.setCardNumber(cardNumTextField.getText());
        creditCard.setCardHolderName(cardHolderNameTextField.getText());
        creditCard.setCVV(cardCvvTextField.getText());
        creditCard.setExpiryDate(cardExpiryTextField.getText());
        creditCard.setIssueDate(cardIssueTextField.getText());
        
        JOptionPane.showMessageDialog(null,"Credit card details added successfully!");
    }//GEN-LAST:event_addCreditCardBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCreditCardBtn;
    private javax.swing.JLabel addCreditCardLabel;
    private javax.swing.JTextField cardCvvTextField;
    private javax.swing.JTextField cardExpiryTextField;
    private javax.swing.JTextField cardHolderNameTextField;
    private javax.swing.JTextField cardIssueTextField;
    private javax.swing.JTextField cardNumTextField;
    private javax.swing.JPanel createCreditJPanel;
    private javax.swing.JLabel creditCardCvvLabel;
    private javax.swing.JLabel creditCardExpiryLabel;
    private javax.swing.JLabel creditCardHolderLabel;
    private javax.swing.JLabel creditCardIssueLabel;
    private javax.swing.JLabel creditCardNumLabel;
    // End of variables declaration//GEN-END:variables
}
