/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import UserApplication.*;
import java.awt.Dimension;
import javax.swing.JScrollPane;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Menita Koonani
 */
public class ViewAllDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAllDetailsJPanel
     */
    public ViewAllDetailsJPanel(Person person) {
        initComponents();
        displayAllDetails(person);
    }
    
    public void displayAllDetails(Person person){
        
        viewDetailsScrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        viewDetailsScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        viewDetailsMainPanel.add(viewDetailsScrollPane);
        
        firstNameTextField.setText(person.getFirstName());
        lastNameTextField.setText(person.getLastName());
        emailTextField.setText(person.getEmailId());
        phoneTextField.setText(person.getPhoneNumber());
        dobDateChooser.setDate(person.getDateOfBirth());
        
        ImageIcon photo = new ImageIcon(person.getPhotoPath());
        JLabel photoContentLabel = new JLabel("Image", photo, JLabel.CENTER);
        photoPanel.add(photoContentLabel);
        
        Address address = person.getAddress();
        if(address!=null)
        {
            streetNameTextField.setText(address.getStreetName());
            aptNumTextField.setText(address.getApartmentNum());
            cityTextField.setText(address.getCity());
            stateTextField.setText(address.getState());
            countryTextField.setText(address.getCountry());
            zipcodeTextField.setText(address.getZipCode());    
        }
        
        License license = person.getLicense();
        if(license!=null)
        {
            licenseExpiryDateChooser.setDate(license.getExpiryDate());
            licenseIssueDateChooser.setDate(license.getIssueDate());
            licenseNameTextField.setText(license.getLicenseName());
            licenseNumTextField.setText(license.getLicenseNumber());
        }

        CreditCard creditCard = person.getCreditCard();
        if(creditCard!=null)
        {
            creditCardNumTextField.setText(creditCard.getCardNumber());
            creditCardHolderTextField.setText(creditCard.getCardHolderName());
            creditCardCvvTextField.setText(creditCard.getCVV());
            creditCardIssueDateChooser.setDate(creditCard.getIssueDate());
            creditCardExpiryDateChooser.setDate(creditCard.getExpiryDate());    
        }
        
        FinancialAccounts financialAccounts = person.getFinancialAccounts();
        if(financialAccounts!=null)
        {
            SavingsAccount savingsAccount = financialAccounts.getSavingsAcc();
            if(savingsAccount!=null)
            {
                savAccNumTextField.setText(savingsAccount.getAccNumber());
                savAccStatusTextField.setText(savingsAccount.isActive() ? "Active" : "Inactive");
                savAccCreationDateChooser.setDate(savingsAccount.getCreationDate());
                savDebtInfoTextField.setText(savingsAccount.getDebtAmt());
                saveCreditInfoTeextField.setText(savingsAccount.getCreditAmt());
            }
            CheckingAccount checkingAccount = financialAccounts.getCheckingAcc();
            if(checkingAccount!=null)
            {
                checkAccNumTextField.setText(checkingAccount.getAccNumber());
                checkAccStatusTextField.setText(checkingAccount.isActive() ? "Active" : "Inactive");
                checkAccCreationDateChooser.setDate(checkingAccount.getCreationDate());
                checkDebtInfoTextField.setText(checkingAccount.getDebtAmt());
                checkCreditInfoTextField.setText(checkingAccount.getCreditAmt());
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewDetailsMainPanel = new javax.swing.JPanel();
        viewDetailsScrollPane = new javax.swing.JScrollPane();
        viewAllDetailsJPanel = new javax.swing.JPanel();
        viewUserLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        DOBLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        zipcodeTextField = new javax.swing.JTextField();
        zipcodeLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        countryTextField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        aptNumTextField = new javax.swing.JTextField();
        streetNameTextField = new javax.swing.JTextField();
        streetNameLabel = new javax.swing.JLabel();
        createAddressLabel = new javax.swing.JLabel();
        apartmentNumLabel = new javax.swing.JLabel();
        licenseDetailsLabel = new javax.swing.JLabel();
        licenseNumLabel = new javax.swing.JLabel();
        licenseNumTextField = new javax.swing.JTextField();
        licenseNameTextField = new javax.swing.JTextField();
        licenseNameLabel = new javax.swing.JLabel();
        licenseIssueDateLabel = new javax.swing.JLabel();
        licenseExpiryDateLabel = new javax.swing.JLabel();
        createAddressLabel1 = new javax.swing.JLabel();
        creditCardNumLabel = new javax.swing.JLabel();
        creditCardHolderLabel = new javax.swing.JLabel();
        creditCardCvvLabel = new javax.swing.JLabel();
        creditCardExpiryDateLabel = new javax.swing.JLabel();
        creditCardIssueDateLabel = new javax.swing.JLabel();
        creditCardNumTextField = new javax.swing.JTextField();
        creditCardHolderTextField = new javax.swing.JTextField();
        creditCardCvvTextField = new javax.swing.JTextField();
        savingsAccDEtailsLabel = new javax.swing.JLabel();
        savAccNumLabel = new javax.swing.JLabel();
        savAccNumTextField = new javax.swing.JTextField();
        savAccStatusLabel = new javax.swing.JLabel();
        savAccStatusTextField = new javax.swing.JTextField();
        savDebtInfoLabel = new javax.swing.JLabel();
        savCreationDateLabel = new javax.swing.JLabel();
        savCreditInfoLabel = new javax.swing.JLabel();
        saveCreditInfoTeextField = new javax.swing.JTextField();
        checkingAccDetailLabel = new javax.swing.JLabel();
        checkAccNumLabel = new javax.swing.JLabel();
        checkAccStatusLabel = new javax.swing.JLabel();
        checkAccCreationDateLabel = new javax.swing.JLabel();
        checkDebtInfoLabel = new javax.swing.JLabel();
        checkCreditInfoLabel = new javax.swing.JLabel();
        checkAccStatusTextField = new javax.swing.JTextField();
        checkAccNumTextField = new javax.swing.JTextField();
        checkCreditInfoTextField = new javax.swing.JTextField();
        dobDateChooser = new com.toedter.calendar.JDateChooser();
        creditCardExpiryDateChooser = new com.toedter.calendar.JDateChooser();
        creditCardIssueDateChooser = new com.toedter.calendar.JDateChooser();
        licenseExpiryDateChooser = new com.toedter.calendar.JDateChooser();
        licenseIssueDateChooser = new com.toedter.calendar.JDateChooser();
        checkAccCreationDateChooser = new com.toedter.calendar.JDateChooser();
        savAccCreationDateChooser = new com.toedter.calendar.JDateChooser();
        savDebtInfoTextField = new javax.swing.JTextField();
        checkDebtInfoTextField = new javax.swing.JTextField();
        photoLabel = new javax.swing.JLabel();
        photoPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        viewUserLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewUserLabel.setText("Details of User");

        firstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        firstNameLabel.setText("First Name:");

        lastNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lastNameLabel.setText("Last Name:");

        DOBLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DOBLabel.setText("Date of Birth:");

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailLabel.setText("Email ID:");

        phoneLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        phoneLabel.setText("Phone Number:");

        phoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextFieldActionPerformed(evt);
            }
        });

        zipcodeLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        zipcodeLabel.setText("Zipcode:");

        countryLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        countryLabel.setText("Country:");

        stateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stateLabel.setText("State:");

        cityLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cityLabel.setText("City:");

        streetNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        streetNameLabel.setText("Street Name:");

        createAddressLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createAddressLabel.setText("Address Details");

        apartmentNumLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        apartmentNumLabel.setText("Apartment Number:");

        licenseDetailsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        licenseDetailsLabel.setText("License Details");

        licenseNumLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        licenseNumLabel.setText("License Number:");

        licenseNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        licenseNameLabel.setText("License Name:");

        licenseIssueDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        licenseIssueDateLabel.setText("License Issue Date:");

        licenseExpiryDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        licenseExpiryDateLabel.setText("License Expiry Date:");

        createAddressLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createAddressLabel1.setText("Credit Card Details");

        creditCardNumLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditCardNumLabel.setText("Credit Card Number:");

        creditCardHolderLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditCardHolderLabel.setText("Credit Card Holder Name:");

        creditCardCvvLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditCardCvvLabel.setText("Credit Card CVV:");

        creditCardExpiryDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditCardExpiryDateLabel.setText("Credit Card Expiry Date:");

        creditCardIssueDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditCardIssueDateLabel.setText("Credit Card Issue Date:");

        savingsAccDEtailsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        savingsAccDEtailsLabel.setText("Savings Account Details");

        savAccNumLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savAccNumLabel.setText("Account Number:");

        savAccStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savAccStatusLabel.setText("Account Status:");

        savDebtInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savDebtInfoLabel.setText("Debt Info:");

        savCreationDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savCreationDateLabel.setText("Account Creation Date:");

        savCreditInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savCreditInfoLabel.setText("Credit Info:");

        checkingAccDetailLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkingAccDetailLabel.setText("Checking Account Details");

        checkAccNumLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkAccNumLabel.setText("Account Number:");

        checkAccStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkAccStatusLabel.setText("Account Status:");

        checkAccCreationDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkAccCreationDateLabel.setText("Account Creation Date:");

        checkDebtInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkDebtInfoLabel.setText("Debt Info:");

        checkCreditInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkCreditInfoLabel.setText("Credit Info:");

        photoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        photoLabel.setText("Photo:");

        photoPanel.setBackground(new java.awt.Color(255, 255, 255));
        photoPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        photoPanel.setToolTipText("Image");

        javax.swing.GroupLayout photoPanelLayout = new javax.swing.GroupLayout(photoPanel);
        photoPanel.setLayout(photoPanelLayout);
        photoPanelLayout.setHorizontalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );
        photoPanelLayout.setVerticalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout viewAllDetailsJPanelLayout = new javax.swing.GroupLayout(viewAllDetailsJPanel);
        viewAllDetailsJPanel.setLayout(viewAllDetailsJPanelLayout);
        viewAllDetailsJPanelLayout.setHorizontalGroup(
            viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(firstNameLabel)
                                .addComponent(lastNameLabel))
                            .addComponent(emailLabel)
                            .addComponent(DOBLabel)
                            .addComponent(phoneLabel)
                            .addComponent(photoLabel))
                        .addGap(25, 25, 25)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dobDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(photoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(viewUserLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(createAddressLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                    .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(streetNameLabel)
                                            .addComponent(apartmentNumLabel)
                                            .addComponent(cityLabel)
                                            .addComponent(stateLabel)
                                            .addComponent(countryLabel)
                                            .addComponent(zipcodeLabel))
                                        .addComponent(savAccNumLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(savAccStatusLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(savCreationDateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(savDebtInfoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(savCreditInfoLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(40, 40, 40)
                                    .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(streetNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(aptNumTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cityTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(stateTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(countryTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(zipcodeTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(savAccNumTextField)
                                        .addComponent(savAccStatusTextField)
                                        .addComponent(savAccCreationDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(savDebtInfoTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(saveCreditInfoTeextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(savingsAccDEtailsLabel))))))
                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(createAddressLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(licenseDetailsLabel)
                                    .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(checkAccNumLabel)
                                                        .addComponent(checkDebtInfoLabel)
                                                        .addComponent(checkAccCreationDateLabel)
                                                        .addComponent(checkCreditInfoLabel))
                                                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                                        .addGap(32, 32, 32)
                                                        .addComponent(checkAccStatusLabel)))
                                                .addGap(25, 25, 25)
                                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(checkAccNumTextField)
                                                    .addComponent(checkAccStatusTextField)
                                                    .addComponent(checkAccCreationDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                                    .addComponent(checkDebtInfoTextField)
                                                    .addComponent(checkCreditInfoTextField)))
                                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(creditCardHolderLabel)
                                                    .addComponent(creditCardNumLabel)
                                                    .addComponent(creditCardCvvLabel)
                                                    .addComponent(creditCardIssueDateLabel)
                                                    .addComponent(creditCardExpiryDateLabel))
                                                .addGap(25, 25, 25)
                                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(creditCardCvvTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(creditCardHolderTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(creditCardNumTextField)
                                                    .addComponent(creditCardExpiryDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(creditCardIssueDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                            .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(licenseIssueDateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(licenseExpiryDateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(licenseNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(licenseNumLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGap(25, 25, 25)
                                            .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(licenseNumTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                                .addComponent(licenseNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                                .addComponent(licenseExpiryDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(licenseIssueDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(checkingAccDetailLabel)))
                        .addContainerGap(198, Short.MAX_VALUE))))
        );
        viewAllDetailsJPanelLayout.setVerticalGroup(
            viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewUserLabel)
                    .addComponent(licenseDetailsLabel))
                .addGap(18, 18, 18)
                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameLabel)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLabel)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DOBLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(licenseNumLabel)
                            .addComponent(licenseNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(licenseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(licenseNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(licenseIssueDateLabel)
                            .addComponent(licenseIssueDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(licenseExpiryDateLabel)
                            .addComponent(licenseExpiryDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createAddressLabel1))
                .addGap(18, 18, 18)
                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photoLabel)
                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(creditCardNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(creditCardNumLabel))
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(creditCardHolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(creditCardHolderLabel))
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(creditCardCvvTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(creditCardCvvLabel)))
                            .addComponent(photoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(createAddressLabel)
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(streetNameLabel)
                                    .addComponent(streetNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apartmentNumLabel)
                                    .addComponent(aptNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cityLabel)
                                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(stateLabel)
                                    .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(countryLabel)
                                    .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(zipcodeLabel)
                                    .addComponent(zipcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(savingsAccDEtailsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(savAccNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(savAccNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllDetailsJPanelLayout.createSequentialGroup()
                                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(savAccStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(savAccStatusLabel))
                                        .addGap(18, 18, 18)
                                        .addComponent(savAccCreationDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(savCreationDateLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(savDebtInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(savDebtInfoLabel))
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(saveCreditInfoTeextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(savCreditInfoLabel)))
                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(creditCardExpiryDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(creditCardExpiryDateLabel)))
                                .addGap(15, 15, 15)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(creditCardIssueDateLabel)
                                    .addComponent(creditCardIssueDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addComponent(checkingAccDetailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(checkAccNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(checkAccNumLabel))
                                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(checkAccCreationDateLabel))
                                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(checkAccStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(checkAccStatusLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(checkAccCreationDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(76, 76, 76))
                                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(checkDebtInfoLabel)
                                            .addComponent(checkDebtInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(checkCreditInfoLabel)
                                            .addComponent(checkCreditInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
        );

        viewDetailsScrollPane.setViewportView(viewAllDetailsJPanel);

        javax.swing.GroupLayout viewDetailsMainPanelLayout = new javax.swing.GroupLayout(viewDetailsMainPanel);
        viewDetailsMainPanel.setLayout(viewDetailsMainPanelLayout);
        viewDetailsMainPanelLayout.setHorizontalGroup(
            viewDetailsMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewDetailsMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewDetailsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        viewDetailsMainPanelLayout.setVerticalGroup(
            viewDetailsMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewDetailsMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewDetailsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );

        add(viewDetailsMainPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void savDebtInfoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savDebtInfoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savDebtInfoTextFieldActionPerformed

    private void phoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOBLabel;
    private javax.swing.JLabel apartmentNumLabel;
    private javax.swing.JTextField aptNumTextField;
    private com.toedter.calendar.JDateChooser checkAccCreationDateChooser;
    private javax.swing.JLabel checkAccCreationDateLabel;
    private javax.swing.JLabel checkAccNumLabel;
    private javax.swing.JTextField checkAccNumTextField;
    private javax.swing.JLabel checkAccStatusLabel;
    private javax.swing.JTextField checkAccStatusTextField;
    private javax.swing.JLabel checkCreditInfoLabel;
    private javax.swing.JTextField checkCreditInfoTextField;
    private javax.swing.JLabel checkDebtInfoLabel;
    private javax.swing.JTextField checkDebtInfoTextField;
    private javax.swing.JLabel checkingAccDetailLabel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JLabel createAddressLabel;
    private javax.swing.JLabel createAddressLabel1;
    private javax.swing.JLabel creditCardCvvLabel;
    private javax.swing.JTextField creditCardCvvTextField;
    private com.toedter.calendar.JDateChooser creditCardExpiryDateChooser;
    private javax.swing.JLabel creditCardExpiryDateLabel;
    private javax.swing.JLabel creditCardHolderLabel;
    private javax.swing.JTextField creditCardHolderTextField;
    private com.toedter.calendar.JDateChooser creditCardIssueDateChooser;
    private javax.swing.JLabel creditCardIssueDateLabel;
    private javax.swing.JLabel creditCardNumLabel;
    private javax.swing.JTextField creditCardNumTextField;
    private com.toedter.calendar.JDateChooser dobDateChooser;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel licenseDetailsLabel;
    private com.toedter.calendar.JDateChooser licenseExpiryDateChooser;
    private javax.swing.JLabel licenseExpiryDateLabel;
    private com.toedter.calendar.JDateChooser licenseIssueDateChooser;
    private javax.swing.JLabel licenseIssueDateLabel;
    private javax.swing.JLabel licenseNameLabel;
    private javax.swing.JTextField licenseNameTextField;
    private javax.swing.JLabel licenseNumLabel;
    private javax.swing.JTextField licenseNumTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JPanel photoPanel;
    private com.toedter.calendar.JDateChooser savAccCreationDateChooser;
    private javax.swing.JLabel savAccNumLabel;
    private javax.swing.JTextField savAccNumTextField;
    private javax.swing.JLabel savAccStatusLabel;
    private javax.swing.JTextField savAccStatusTextField;
    private javax.swing.JLabel savCreationDateLabel;
    private javax.swing.JLabel savCreditInfoLabel;
    private javax.swing.JLabel savDebtInfoLabel;
    private javax.swing.JTextField savDebtInfoTextField;
    private javax.swing.JTextField saveCreditInfoTeextField;
    private javax.swing.JLabel savingsAccDEtailsLabel;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JLabel streetNameLabel;
    private javax.swing.JTextField streetNameTextField;
    private javax.swing.JPanel viewAllDetailsJPanel;
    private javax.swing.JPanel viewDetailsMainPanel;
    private javax.swing.JScrollPane viewDetailsScrollPane;
    private javax.swing.JLabel viewUserLabel;
    private javax.swing.JLabel zipcodeLabel;
    private javax.swing.JTextField zipcodeTextField;
    // End of variables declaration//GEN-END:variables
}
