/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import UserApplication.*;

/**
 *
 * @author Menita Koonani
 */
public class ViewAllDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAllDetailsJPanel
     */
    private Person person;
    public ViewAllDetailsJPanel(Person person) {
        initComponents();
        displayAllDetails(person);
    }
    
    public void displayAllDetails(Person person){
        
        firstNameTextField.setText(person.getFirstName());
        lastNameTextField.setText(person.getLastName());
        emailTextField.setText(person.getEmailId());
        phoneTextField.setText(person.getPhoneNumber());
        dobTextField.setText(person.getDateOfBirth());
        
        Address address = person.getAddress();
        if(address!=null)
        {
            streetNameTextField.setText(address.getStreetName());
            aptNumTextField.setText(address.getApartmentNum());
            cityTextField.setText(address.getCity());
            stateTextField.setText(address.getState());
            countryTextField.setText(address.getCountry());
            zipcodeTextField.setText(address.getZipCode());    
        }
        
        License license = person.getLicense();
        if(license!=null)
        {
            licenseExpiryDateLabel.setText(license.getExpiryDate());
            licenseIssueDateTextField.setText(license.getIssueDate());
            licenseNameTextField.setText(license.getLicenseName());
            licenseNumTextField.setText(license.getLicenseNumber());
        }

        CreditCard creditCard = person.getCreditCard();
        if(creditCard!=null)
        {
            creditCardNumTextField.setText(creditCard.getCardNumber());
            creditCardHolderTextField.setText(creditCard.getCardHolderName());
            creditCardCvvTextField.setText(creditCard.getCVV());
            creditCardIssueTextField.setText(creditCard.getIssueDate());
            creditCardExpiryTextField.setText(creditCard.getExpiryDate());    
        }
        
        FinancialAccounts financialAccounts = person.getFinancialAccounts();
        if(financialAccounts!=null)
        {
            SavingsAccount savingsAccount = financialAccounts.getSavingsAcc();
            if(savingsAccount!=null)
            {
                savAccNumTextField.setText(savingsAccount.getAccNumber());
                savAccStatusTextField.setText(savingsAccount.isActive() ? "Active" : "Inactive");
                savCreationDateTextField.setText(savingsAccount.getCreationDate());
                savDebtInfoTextField.setText(savingsAccount.getDebtAmt());
                saveCreditInfoTeextField.setText(savingsAccount.getCreditAmt());
            }
            CheckingAccount checkingAccount = financialAccounts.getCheckingAcc();
            if(checkingAccount!=null)
            {
                checkAccNumTextField.setText(checkingAccount.getAccNumber());
                checkAccStatusTextField.setText(checkingAccount.isActive() ? "Active" : "Inactive");
                checkCreationDateTextField.setText(checkingAccount.getCreationDate());
                checkDebtInfoTextField.setText(checkingAccount.getDebtAmt());
                checkCreditInfoTextField.setText(checkingAccount.getCreditAmt());
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewAllDetailsJPanel = new javax.swing.JPanel();
        viewUserLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        DOBLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        dobTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        zipcodeTextField = new javax.swing.JTextField();
        zipcodeLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        countryTextField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        aptNumTextField = new javax.swing.JTextField();
        streetNameTextField = new javax.swing.JTextField();
        streetNameLabel = new javax.swing.JLabel();
        createAddressLabel = new javax.swing.JLabel();
        apartmentNumLabel = new javax.swing.JLabel();
        licenseDetailsLabel = new javax.swing.JLabel();
        licenseNumLabel = new javax.swing.JLabel();
        licenseNumTextField = new javax.swing.JTextField();
        licenseNameTextField = new javax.swing.JTextField();
        licenseNameLabel = new javax.swing.JLabel();
        licenseIssueDateLabel = new javax.swing.JLabel();
        licenseIssueDateTextField = new javax.swing.JTextField();
        licenseExpiryDateTextField1 = new javax.swing.JTextField();
        licenseExpiryDateLabel = new javax.swing.JLabel();
        createAddressLabel1 = new javax.swing.JLabel();
        creditCardNumLabel = new javax.swing.JLabel();
        creditCardHolderLabel = new javax.swing.JLabel();
        creditCardCvvLabel = new javax.swing.JLabel();
        creditCardExpiryDateLabel = new javax.swing.JLabel();
        creditCardIssueDateLabel = new javax.swing.JLabel();
        creditCardNumTextField = new javax.swing.JTextField();
        creditCardHolderTextField = new javax.swing.JTextField();
        creditCardCvvTextField = new javax.swing.JTextField();
        creditCardExpiryTextField = new javax.swing.JTextField();
        creditCardIssueTextField = new javax.swing.JTextField();
        userPhotoLabel = new javax.swing.JLabel();
        photoTextField = new javax.swing.JTextField();
        savingsAccDEtailsLabel = new javax.swing.JLabel();
        savAccNumLabel = new javax.swing.JLabel();
        savAccNumTextField = new javax.swing.JTextField();
        savAccStatusLabel = new javax.swing.JLabel();
        savAccStatusTextField = new javax.swing.JTextField();
        savDebtInfoLabel = new javax.swing.JLabel();
        savCreationDateTextField = new javax.swing.JTextField();
        savCreationDateLabel = new javax.swing.JLabel();
        savDebtInfoTextField = new javax.swing.JTextField();
        savCreditInfoLabel = new javax.swing.JLabel();
        saveCreditInfoTeextField = new javax.swing.JTextField();
        checkingAccDetailLabel = new javax.swing.JLabel();
        checkAccNumLabel = new javax.swing.JLabel();
        checkAccStatusLabel = new javax.swing.JLabel();
        checkAccCreationDateLabel = new javax.swing.JLabel();
        checkDebtInfoLabel = new javax.swing.JLabel();
        checkCreditInfoLabel = new javax.swing.JLabel();
        checkCreationDateTextField = new javax.swing.JTextField();
        checkAccStatusTextField = new javax.swing.JTextField();
        checkAccNumTextField = new javax.swing.JTextField();
        checkDebtInfoTextField = new javax.swing.JTextField();
        checkCreditInfoTextField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        viewUserLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        viewUserLabel.setText("Details of User");

        firstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        firstNameLabel.setText("First Name:");

        lastNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lastNameLabel.setText("Last Name:");

        DOBLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DOBLabel.setText("Date of Birth:");

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailLabel.setText("Email ID:");

        phoneLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        phoneLabel.setText("Phone Number:");

        phoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextFieldActionPerformed(evt);
            }
        });

        zipcodeLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        zipcodeLabel.setText("Zipcode:");

        countryLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        countryLabel.setText("Country:");

        stateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stateLabel.setText("State:");

        cityLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cityLabel.setText("City:");

        streetNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        streetNameLabel.setText("Street Name:");

        createAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createAddressLabel.setText("Address Details");

        apartmentNumLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        apartmentNumLabel.setText("Apartment Number:");

        licenseDetailsLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        licenseDetailsLabel.setText("License Details");

        licenseNumLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        licenseNumLabel.setText("License Number:");

        licenseNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        licenseNameLabel.setText("License Name:");

        licenseIssueDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        licenseIssueDateLabel.setText("License Issue Date:");

        licenseExpiryDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        licenseExpiryDateLabel.setText("License Expiry Date:");

        createAddressLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createAddressLabel1.setText("Credit Card Details");

        creditCardNumLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditCardNumLabel.setText("Credit Card Number:");

        creditCardHolderLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditCardHolderLabel.setText("Credit Card Holder Name:");

        creditCardCvvLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditCardCvvLabel.setText("Credit Card CVV:");

        creditCardExpiryDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditCardExpiryDateLabel.setText("Credit Card Expiry Date:");

        creditCardIssueDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditCardIssueDateLabel.setText("Credit Card Issue Date:");

        userPhotoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userPhotoLabel.setText("Photo:");

        photoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoTextFieldActionPerformed(evt);
            }
        });

        savingsAccDEtailsLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        savingsAccDEtailsLabel.setText("Savings Account Details");

        savAccNumLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savAccNumLabel.setText("Account Number:");

        savAccStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savAccStatusLabel.setText("Account Status:");

        savDebtInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savDebtInfoLabel.setText("Debt Info:");

        savCreationDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savCreationDateLabel.setText("Account Creation Date:");

        savDebtInfoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savDebtInfoTextFieldActionPerformed(evt);
            }
        });

        savCreditInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savCreditInfoLabel.setText("Credit Info:");

        checkingAccDetailLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        checkingAccDetailLabel.setText("Checking Account Details");

        checkAccNumLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkAccNumLabel.setText("Account Number:");

        checkAccStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkAccStatusLabel.setText("Account Status:");

        checkAccCreationDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkAccCreationDateLabel.setText("Account Creation Date:");

        checkDebtInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkDebtInfoLabel.setText("Debt Info:");

        checkCreditInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkCreditInfoLabel.setText("Credit Info:");

        javax.swing.GroupLayout viewAllDetailsJPanelLayout = new javax.swing.GroupLayout(viewAllDetailsJPanel);
        viewAllDetailsJPanel.setLayout(viewAllDetailsJPanelLayout);
        viewAllDetailsJPanelLayout.setHorizontalGroup(
            viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(firstNameLabel)
                                .addComponent(lastNameLabel))
                            .addComponent(emailLabel)
                            .addComponent(DOBLabel)
                            .addComponent(phoneLabel)
                            .addComponent(userPhotoLabel)
                            .addComponent(streetNameLabel)
                            .addComponent(apartmentNumLabel)
                            .addComponent(cityLabel)
                            .addComponent(stateLabel)
                            .addComponent(countryLabel)
                            .addComponent(zipcodeLabel))
                        .addGap(76, 76, 76)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(streetNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(aptNumTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(cityTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(stateTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(countryTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(zipcodeTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(photoTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dobTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(viewUserLabel))
                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(createAddressLabel)))
                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createAddressLabel1)
                        .addGap(136, 136, 136))
                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(licenseIssueDateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(licenseExpiryDateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(licenseNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(licenseNumLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(29, 29, 29)
                                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(licenseNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(licenseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(licenseIssueDateTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(licenseExpiryDateTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(creditCardHolderLabel)
                                            .addComponent(creditCardNumLabel)
                                            .addComponent(creditCardCvvLabel)
                                            .addComponent(creditCardIssueDateLabel)
                                            .addComponent(creditCardExpiryDateLabel))
                                        .addGap(36, 36, 36)
                                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(creditCardIssueTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(creditCardExpiryTextField)
                                            .addComponent(creditCardCvvTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(creditCardHolderTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(creditCardNumTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllDetailsJPanelLayout.createSequentialGroup()
                                .addComponent(licenseDetailsLabel)
                                .addGap(169, 169, 169))))))
            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(savingsAccDEtailsLabel)
                        .addGap(39, 39, 39))
                    .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                            .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(savAccStatusLabel)
                                .addComponent(savAccNumLabel)
                                .addComponent(savDebtInfoLabel)
                                .addComponent(savCreationDateLabel))
                            .addGap(47, 47, 47)
                            .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(savAccNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(savAccStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(savCreationDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(savDebtInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                            .addComponent(savCreditInfoLabel)
                            .addGap(47, 47, 47)
                            .addComponent(saveCreditInfoTeextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(checkingAccDetailLabel)
                        .addGap(39, 39, 39))
                    .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                            .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(checkAccStatusLabel)
                                .addComponent(checkAccNumLabel)
                                .addComponent(checkDebtInfoLabel)
                                .addComponent(checkAccCreationDateLabel))
                            .addGap(47, 47, 47)
                            .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(checkAccNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkAccStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkCreationDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkDebtInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                            .addComponent(checkCreditInfoLabel)
                            .addGap(47, 47, 47)
                            .addComponent(checkCreditInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(96, 96, 96))
        );
        viewAllDetailsJPanelLayout.setVerticalGroup(
            viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewUserLabel)
                            .addComponent(licenseDetailsLabel))
                        .addGap(29, 29, 29)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firstNameLabel)
                                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lastNameLabel)
                                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DOBLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emailLabel)
                                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(licenseNumLabel)
                                    .addComponent(licenseNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(licenseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(licenseNameLabel))
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(licenseIssueDateLabel)
                                    .addComponent(licenseIssueDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(licenseExpiryDateLabel)
                                    .addComponent(licenseExpiryDateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLabel)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addComponent(createAddressLabel1)
                        .addGap(8, 8, 8)))
                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userPhotoLabel)
                            .addComponent(photoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(createAddressLabel)
                        .addGap(18, 18, 18)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(streetNameLabel)
                            .addComponent(streetNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apartmentNumLabel)
                            .addComponent(aptNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityLabel)
                            .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stateLabel)
                            .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countryLabel)
                            .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zipcodeLabel)
                            .addComponent(zipcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                .addComponent(creditCardNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(creditCardHolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(creditCardCvvTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(creditCardExpiryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(creditCardIssueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(creditCardIssueDateLabel)))
                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(creditCardExpiryDateLabel))
                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                .addComponent(creditCardNumLabel)
                                .addGap(25, 25, 25)
                                .addComponent(creditCardHolderLabel)
                                .addGap(23, 23, 23)
                                .addComponent(creditCardCvvLabel)))))
                .addGap(50, 50, 50)
                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                .addComponent(savingsAccDEtailsLabel)
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(savAccNumLabel)
                                    .addComponent(savAccNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(savAccStatusLabel)
                                    .addComponent(savAccStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(savCreationDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(savCreationDateLabel))
                        .addGap(18, 18, 18)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savDebtInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(savDebtInfoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveCreditInfoTeextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(savCreditInfoLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllDetailsJPanelLayout.createSequentialGroup()
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(viewAllDetailsJPanelLayout.createSequentialGroup()
                                .addComponent(checkingAccDetailLabel)
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(checkAccNumLabel)
                                    .addComponent(checkAccNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(checkAccStatusLabel)
                                    .addComponent(checkAccStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(checkCreationDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(checkAccCreationDateLabel))
                        .addGap(18, 18, 18)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkDebtInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkDebtInfoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(viewAllDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkCreditInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkCreditInfoLabel)))))
        );

        add(viewAllDetailsJPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void phoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTextFieldActionPerformed

    private void photoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photoTextFieldActionPerformed

    private void savDebtInfoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savDebtInfoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savDebtInfoTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOBLabel;
    private javax.swing.JLabel apartmentNumLabel;
    private javax.swing.JTextField aptNumTextField;
    private javax.swing.JLabel checkAccCreationDateLabel;
    private javax.swing.JLabel checkAccNumLabel;
    private javax.swing.JTextField checkAccNumTextField;
    private javax.swing.JLabel checkAccStatusLabel;
    private javax.swing.JTextField checkAccStatusTextField;
    private javax.swing.JTextField checkCreationDateTextField;
    private javax.swing.JLabel checkCreditInfoLabel;
    private javax.swing.JTextField checkCreditInfoTextField;
    private javax.swing.JLabel checkDebtInfoLabel;
    private javax.swing.JTextField checkDebtInfoTextField;
    private javax.swing.JLabel checkingAccDetailLabel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JLabel createAddressLabel;
    private javax.swing.JLabel createAddressLabel1;
    private javax.swing.JLabel creditCardCvvLabel;
    private javax.swing.JTextField creditCardCvvTextField;
    private javax.swing.JLabel creditCardExpiryDateLabel;
    private javax.swing.JTextField creditCardExpiryTextField;
    private javax.swing.JLabel creditCardHolderLabel;
    private javax.swing.JTextField creditCardHolderTextField;
    private javax.swing.JLabel creditCardIssueDateLabel;
    private javax.swing.JTextField creditCardIssueTextField;
    private javax.swing.JLabel creditCardNumLabel;
    private javax.swing.JTextField creditCardNumTextField;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel licenseDetailsLabel;
    private javax.swing.JLabel licenseExpiryDateLabel;
    private javax.swing.JTextField licenseExpiryDateTextField1;
    private javax.swing.JLabel licenseIssueDateLabel;
    private javax.swing.JTextField licenseIssueDateTextField;
    private javax.swing.JLabel licenseNameLabel;
    private javax.swing.JTextField licenseNameTextField;
    private javax.swing.JLabel licenseNumLabel;
    private javax.swing.JTextField licenseNumTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField photoTextField;
    private javax.swing.JLabel savAccNumLabel;
    private javax.swing.JTextField savAccNumTextField;
    private javax.swing.JLabel savAccStatusLabel;
    private javax.swing.JTextField savAccStatusTextField;
    private javax.swing.JLabel savCreationDateLabel;
    private javax.swing.JTextField savCreationDateTextField;
    private javax.swing.JLabel savCreditInfoLabel;
    private javax.swing.JLabel savDebtInfoLabel;
    private javax.swing.JTextField savDebtInfoTextField;
    private javax.swing.JTextField saveCreditInfoTeextField;
    private javax.swing.JLabel savingsAccDEtailsLabel;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JLabel streetNameLabel;
    private javax.swing.JTextField streetNameTextField;
    private javax.swing.JLabel userPhotoLabel;
    private javax.swing.JPanel viewAllDetailsJPanel;
    private javax.swing.JLabel viewUserLabel;
    private javax.swing.JLabel zipcodeLabel;
    private javax.swing.JTextField zipcodeTextField;
    // End of variables declaration//GEN-END:variables
}
