/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;
import Business.VitalSigns;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Menita Koonani
 */
public class ViewVitalSignPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewVitalSignPanel
     */
    private VitalSignHistory vitalSignHistory;

    public ViewVitalSignPanel(VitalSignHistory vitalSignHistory) {
        initComponents();
        this.vitalSignHistory = vitalSignHistory;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel jTable = (DefaultTableModel) tableModel.getModel();
        //starting the population form row 0
        jTable.setRowCount(0);

        for (VitalSigns eachVitalSign : vitalSignHistory.getVitalSignArrayList()) {
            Object row[] = new Object[2];
            //setting the object to the first row as we need to access all the other attributes of that particular object
            row[0] = eachVitalSign;
            row[1] = eachVitalSign.getBloodPressure();
            jTable.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPanelHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableModel = new javax.swing.JTable();
        viewVitalSignBtn = new javax.swing.JButton();
        deleteVitalSignBtn = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        pulseField = new javax.swing.JTextField();
        tempField = new javax.swing.JTextField();
        BPLabel = new javax.swing.JLabel();
        tempLabel = new javax.swing.JLabel();
        pulseLabel = new javax.swing.JLabel();
        BPField = new javax.swing.JTextField();

        viewPanelHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewPanelHeader.setText("View Vital Sign");

        tableModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Date", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableModel);
        if (tableModel.getColumnModel().getColumnCount() > 0) {
            tableModel.getColumnModel().getColumn(0).setResizable(false);
            tableModel.getColumnModel().getColumn(1).setResizable(false);
        }

        viewVitalSignBtn.setText("View Details");
        viewVitalSignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVitalSignBtnActionPerformed(evt);
            }
        });

        deleteVitalSignBtn.setText("Delete");
        deleteVitalSignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVitalSignBtnActionPerformed(evt);
            }
        });

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateLabel.setText("Date");

        BPLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BPLabel.setText("Blood Pressure");

        tempLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tempLabel.setText("Temperature");

        pulseLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pulseLabel.setText("Pulse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(viewPanelHeader))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addComponent(viewVitalSignBtn)
                                .addGap(31, 31, 31)
                                .addComponent(deleteVitalSignBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tempLabel)
                            .addComponent(BPLabel)
                            .addComponent(pulseLabel)
                            .addComponent(dateLabel))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pulseField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tempField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BPField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(viewPanelHeader)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewVitalSignBtn)
                    .addComponent(deleteVitalSignBtn))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempLabel)
                    .addComponent(tempField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BPLabel)
                    .addComponent(BPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pulseLabel)
                    .addComponent(pulseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewVitalSignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVitalSignBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableModel.getSelectedRow();
        if (selectedRow >= 0) {
            VitalSigns vs = (VitalSigns) tableModel.getValueAt(selectedRow, 0);
            BPField.setText(String.valueOf(vs.getBloodPressure()));
            tempField.setText(String.valueOf(vs.getTemperatue()));
            pulseField.setText(String.valueOf(vs.getPulse()));
            dateField.setText(String.valueOf(vs.getDate()));
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!!");
        }
    }//GEN-LAST:event_viewVitalSignBtnActionPerformed

    private void deleteVitalSignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVitalSignBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableModel.getSelectedRow();
        if (selectedRow >= 0) {
            VitalSigns vs = (VitalSigns) tableModel.getValueAt(selectedRow, 0);
            vitalSignHistory.deleteVitals(vs);
            JOptionPane.showMessageDialog(null, "Vital sign is deleted!");
            populateTable();
            
            tempField.setText("");
            BPField.setText("");
            pulseField.setText("");
            dateField.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!!");
        }
    }//GEN-LAST:event_deleteVitalSignBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BPField;
    private javax.swing.JLabel BPLabel;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton deleteVitalSignBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pulseField;
    private javax.swing.JLabel pulseLabel;
    private javax.swing.JTable tableModel;
    private javax.swing.JTextField tempField;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JLabel viewPanelHeader;
    private javax.swing.JButton viewVitalSignBtn;
    // End of variables declaration//GEN-END:variables
}
