/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Disease.Disease;
import Business.Enterprise.HospitalEnterprise;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Menita Koonani
 */
public class ManageDiseasesJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private HospitalEnterprise enterprise;

    /**
     * Creates new form ManageDiseasesJPanel
     */
    public ManageDiseasesJPanel(JPanel userProcessContianer, HospitalEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContianer;
        this.enterprise = enterprise;
        populateDiseaseTable();
    }

    public void populateDiseaseTable() {
        DefaultTableModel jTable = (DefaultTableModel) diseaseTable.getModel();
        jTable.setRowCount(0);
        for (Disease eachDisease : enterprise.getDiseaseCatalog().getDiseaseList()) {
            Object[] row = new Object[2];
            row[0] = eachDisease;
            jTable.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        diseaseNameField = new javax.swing.JTextField();
        addDiseaseBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        diseaseTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Disease Name : ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 90, 20));
        add(diseaseNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 170, -1));

        addDiseaseBtn.setText("Add Disease");
        addDiseaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDiseaseBtnActionPerformed(evt);
            }
        });
        add(addDiseaseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 120, -1));

        diseaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Disease"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(diseaseTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, 130));

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addDiseaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDiseaseBtnActionPerformed
        String diseaseName = diseaseNameField.getText();
        if (diseaseName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Disease name cannot be empty!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        enterprise.getDiseaseCatalog().newDisease(diseaseName);
        diseaseNameField.setText("");
        populateDiseaseTable();
    }//GEN-LAST:event_addDiseaseBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDiseaseBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField diseaseNameField;
    private javax.swing.JTable diseaseTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
