/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.UserDirectory;

import Business.Business;
import Business.User;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Menita Koonani
 */
public class ManageUserAccountDirectory extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserAccountDirectory
     */
    JPanel UserProcessContainer;
    Business business;
    User user;

    public ManageUserAccountDirectory(JPanel UserProcessContainer, Business business, User user) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.business = business;
        this.user = user;
        populateUserAccountDir();
    }

    public void populateUserAccountDir() {
        DefaultTableModel manageUserAccTable = (DefaultTableModel) manageUsersTable.getModel();
        manageUserAccTable.setRowCount(0);

        for (User eachUser : business.getUserDirectory().getUserList()) {
            Object row[] = new Object[5];

            row[0] = eachUser;
            row[1] = eachUser.getUsername();
            row[2] = generatePassword(Arrays.toString(eachUser.getUserPassword()));
            row[3] = eachUser.getUserRole();
            row[4] = eachUser.isActive();

            manageUserAccTable.addRow(row);
        }
    }

    public String generatePassword(String password) {
        String encryptedPwd = "";
        for (int i = 0; i < password.length(); i++) {
            encryptedPwd = encryptedPwd + "*";
        }
        return encryptedPwd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPageHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageUsersTable = new javax.swing.JTable();
        findUserAcc = new javax.swing.JButton();
        newUserAcc = new javax.swing.JButton();
        updateUserAcc = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPageHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loginPageHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginPageHeader.setText("Manage User Account Directory");
        add(loginPageHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 24, 760, 60));

        manageUsersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Username", "Password", "Account Role", "Account Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageUsersTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 140, 600, 180));

        findUserAcc.setBackground(new java.awt.Color(0, 153, 153));
        findUserAcc.setText("Find User Account >>");
        findUserAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findUserAccActionPerformed(evt);
            }
        });
        add(findUserAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 180, -1));

        newUserAcc.setBackground(new java.awt.Color(0, 153, 153));
        newUserAcc.setText("New User Account >>");
        newUserAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserAccActionPerformed(evt);
            }
        });
        add(newUserAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 180, -1));

        updateUserAcc.setBackground(new java.awt.Color(0, 153, 153));
        updateUserAcc.setText("Update User Account >>");
        updateUserAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserAccActionPerformed(evt);
            }
        });
        add(updateUserAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 180, -1));

        backBtn.setBackground(new java.awt.Color(0, 153, 153));
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 383, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void updateUserAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserAccActionPerformed
        // TODO add your handling code here:
        int selectedRow = manageUsersTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        User selectedUser = (User) manageUsersTable.getValueAt(selectedRow, 0);
        UpdateUserAccountJPanel updateUserAccPanel = new UpdateUserAccountJPanel(UserProcessContainer, business, selectedUser);
        CardLayout cardLayout = (CardLayout) UserProcessContainer.getLayout();
        UserProcessContainer.add("UpdateUserAccountPanel", updateUserAccPanel);
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_updateUserAccActionPerformed

    private void findUserAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findUserAccActionPerformed
        // TODO add your handling code here:
        FindUserJPanel findUserPanel = new FindUserJPanel(UserProcessContainer, business);
        UserProcessContainer.add("FiendUserPanel", findUserPanel);
        CardLayout cardLayout = (CardLayout) UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_findUserAccActionPerformed

    private void newUserAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserAccActionPerformed
        // TODO add your handling code here:
        NewUserAccountJPanel newUserAccPanel = new NewUserAccountJPanel(UserProcessContainer, business);
        CardLayout cardLayout = (CardLayout) UserProcessContainer.getLayout();
        UserProcessContainer.add("NewUserAccPanel", newUserAccPanel);
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_newUserAccActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        Component[] componentArray = UserProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        UserWorkAreaJPanel userWorkAreaPanel = (UserWorkAreaJPanel) component;
        userWorkAreaPanel.populateUserWorkAreaPanel();
        CardLayout cardLayout = (CardLayout) UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton findUserAcc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginPageHeader;
    private javax.swing.JTable manageUsersTable;
    private javax.swing.JButton newUserAcc;
    private javax.swing.JButton updateUserAcc;
    // End of variables declaration//GEN-END:variables
}
