/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.UserDirectory;

import Business.Business;
import Business.Person;
import Business.User;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Menita Koonani
 */
public class NewUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewUserAccountJPanel
     */
    JPanel UserProcessContainer;
    Business business;

    public NewUserAccountJPanel(JPanel UserProcessContainer, Business business) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.business = business;
        populateNewUserPanel();
    }

    // populating the person list chooser
    public void populatePersonList() {
        personChooser.removeAllItems();
        personChooser.addItem("Select");
        for (Person eachPerson : business.getPersonDirectory().getPersonList()) {
            personChooser.addItem(eachPerson.getFirstName() + " " + eachPerson.getLastName());
        }
    }

    // populating the user role chooser
    public void populateUserRole() {
        userRoleChooser.removeAllItems();
        userRoleChooser.addItem("Select");
        for (String userRole : business.getUserDirectory().getUserRole()) {
            userRoleChooser.addItem(userRole);
        }
    }

    // populating the new user panel
    public void populateNewUserPanel() {
        populatePersonList();
        populateUserRole();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newUserAccHeader = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userRoleChooser = new javax.swing.JComboBox<>();
        personChooser = new javax.swing.JComboBox<>();
        usernameField = new javax.swing.JTextField();
        createUserAccBtn = new javax.swing.JButton();
        cancelUserAccBtn = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newUserAccHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newUserAccHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newUserAccHeader.setText("New User Account");
        add(newUserAccHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 24, 760, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Select a role : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Select a person : ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("User Name : ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Password : ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 200, 30));

        userRoleChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userRoleChooserActionPerformed(evt);
            }
        });
        add(userRoleChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 230, 30));

        add(personChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 230, 30));
        add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 230, 30));

        createUserAccBtn.setBackground(new java.awt.Color(0, 153, 153));
        createUserAccBtn.setText("Create");
        createUserAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserAccBtnActionPerformed(evt);
            }
        });
        add(createUserAccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 120, 30));

        cancelUserAccBtn.setBackground(new java.awt.Color(0, 153, 153));
        cancelUserAccBtn.setText("<< Cancel");
        cancelUserAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelUserAccBtnActionPerformed(evt);
            }
        });
        add(cancelUserAccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 110, 30));
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 230, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void userRoleChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userRoleChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userRoleChooserActionPerformed

    private void cancelUserAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelUserAccBtnActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        Component[] componentArray = UserProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageUserAccountDirectory manageUserAccDir = (ManageUserAccountDirectory) component;
        manageUserAccDir.populateUserAccountDir();
        CardLayout cardLayout = (CardLayout) UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_cancelUserAccBtnActionPerformed

    private void createUserAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserAccBtnActionPerformed
        // TODO add your handling code here
        String selectedPerson = (String) personChooser.getSelectedItem();
        String userName = usernameField.getText();
        char[] password = passwordField.getPassword();
        String userRole = (String) userRoleChooser.getSelectedItem();

        if (selectedPerson.equalsIgnoreCase("Select")) {
            JOptionPane.showMessageDialog(null, "Choose a person!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (userName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "The username field cannot be empty!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (userRole.equalsIgnoreCase("Select")) {
            JOptionPane.showMessageDialog(null, "Choose a user role!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (password.length < 6) {
            JOptionPane.showMessageDialog(null, "The password field should be atleast 6 char long", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Person person = business.getPersonDirectory().getPersonByName(selectedPerson);
        User newUser = business.getUserDirectory().addNewUser();
        newUser.setUsername(userName);
        newUser.setUserPassword(password);
        newUser.setUserRole(userRole);
        newUser.setPerson(person);

        JOptionPane.showMessageDialog(null, "New user successfully added!");
        resetFields();
    }//GEN-LAST:event_createUserAccBtnActionPerformed

    public void resetFields() {
        personChooser.setSelectedIndex(0);
        userRoleChooser.setSelectedIndex(0);
        usernameField.setText("");
        passwordField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelUserAccBtn;
    private javax.swing.JButton createUserAccBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel newUserAccHeader;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JComboBox<String> personChooser;
    private javax.swing.JComboBox<String> userRoleChooser;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
