/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.UserDirectory;

import Business.Business;
import Business.Person;
import Business.User;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Menita Koonani
 */
public class UpdateUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateUserAccountJPanel
     */
    JPanel UserProcessContainer;
    Business business;
    User user;
    
    public UpdateUserAccountJPanel(JPanel UserProcessContainer, Business business, User user) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.business = business;
        this.user = user;
        populateUpdateUserPanel();
    }

    // populating the person list chooser
    public void populatePersonList() {
        personChooser.removeAllItems();
        personChooser.addItem("Select");
        for (Person eachPerson : business.getPersonDirectory().getPersonList()) {
            personChooser.addItem(eachPerson.getFirstName() + " " + eachPerson.getLastName());
        }
    }

    // populating the user role chooser
    public void populateUserRole() {
        userRoleChooser.removeAllItems();
        userRoleChooser.addItem("Select");
        for (String userRole : business.getUserDirectory().getUserRole()) {
            userRoleChooser.addItem(userRole);
        }
    }

    // populating the new user panel
    public void populateUpdateUserPanel() {
        populatePersonList();
        populateUserRole();
        Person person = user.getPerson();
        personChooser.setSelectedItem(person.getFirstName() + " " + person.getLastName());
        userRoleChooser.setSelectedItem(user.getUserRole());
        usernameField.setText(user.getUsername());
        passwordField.setText(user.getUserPassword().toString());
        if (user.isActive()) {
            activeStatus.setSelected(true);
        } else {
            disableStatus.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accStatus = new javax.swing.ButtonGroup();
        newUserAccHeader = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userRoleChooser = new javax.swing.JComboBox<>();
        personChooser = new javax.swing.JComboBox<>();
        usernameField = new javax.swing.JTextField();
        updateUserAccBtn = new javax.swing.JButton();
        cancelUserAccBtn = new javax.swing.JButton();
        disableStatus = new javax.swing.JRadioButton();
        activeStatus = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newUserAccHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newUserAccHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newUserAccHeader.setText("Update User Account");
        add(newUserAccHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 24, 760, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Select Account Status : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Select a person : ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("User Name : ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Password : ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 200, 30));

        add(userRoleChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 230, 30));

        add(personChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 230, 30));
        add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 230, 30));

        updateUserAccBtn.setBackground(new java.awt.Color(0, 153, 153));
        updateUserAccBtn.setText("Update");
        updateUserAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserAccBtnActionPerformed(evt);
            }
        });
        add(updateUserAccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 90, 30));

        cancelUserAccBtn.setBackground(new java.awt.Color(0, 153, 153));
        cancelUserAccBtn.setText("<< Cancel");
        cancelUserAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelUserAccBtnActionPerformed(evt);
            }
        });
        add(cancelUserAccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 100, 30));

        accStatus.add(disableStatus);
        disableStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        disableStatus.setText("Disable");
        add(disableStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 80, 30));

        accStatus.add(activeStatus);
        activeStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        activeStatus.setSelected(true);
        activeStatus.setText("Active");
        add(activeStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 273, 80, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Select a role : ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 200, 30));
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 230, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void updateUserAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserAccBtnActionPerformed
        // TODO add your handling code here:
        String selectedPerson = (String) personChooser.getSelectedItem();
        String userName = usernameField.getText();
        char[] password = passwordField.getPassword();
        String userRole = (String) userRoleChooser.getSelectedItem();
        boolean isActive = activeStatus.isSelected();
        
        if (selectedPerson.equalsIgnoreCase("Select")) {
            JOptionPane.showMessageDialog(null, "Choose a person!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (userName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "The username field cannot be empty!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (userRole.equalsIgnoreCase("Select")) {
            JOptionPane.showMessageDialog(null, "Choose a user role!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (password.length < 6) {
            JOptionPane.showMessageDialog(null, "The password field should be atleast 6 char long", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Person person = business.getPersonDirectory().getPersonByName(selectedPerson);
        User newUser = business.getUserDirectory().addNewUser();
        newUser.setUsername(userName);
        newUser.setUserPassword(password);
        newUser.setUserRole(userRole);
        newUser.setPerson(person);
        newUser.setIsActive(isActive);
        
        JOptionPane.showMessageDialog(null, "Person update successfully!");
    }//GEN-LAST:event_updateUserAccBtnActionPerformed

    private void cancelUserAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelUserAccBtnActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        Component[] componentArray = UserProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageUserAccountDirectory manageUserAccDir = (ManageUserAccountDirectory) component;
        manageUserAccDir.populateUserAccountDir();
        CardLayout cardLayout = (CardLayout) UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_cancelUserAccBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup accStatus;
    private javax.swing.JRadioButton activeStatus;
    private javax.swing.JButton cancelUserAccBtn;
    private javax.swing.JRadioButton disableStatus;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel newUserAccHeader;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JComboBox<String> personChooser;
    private javax.swing.JButton updateUserAccBtn;
    private javax.swing.JComboBox<String> userRoleChooser;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
