/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageFlights;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Flight;
import Business.Schedule;
import UserInterface.ManageAirliners.CreateNewAirlinerJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Menita Koonani
 */
public class CreateNewFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateFlightJPanel
     */
    private javax.swing.JPanel CardSequenceJPanel;
    private AirlinerDirectory airlinerDirectory;

    public CreateNewFlightJPanel(javax.swing.JPanel CardSequenceJPanel, AirlinerDirectory airlinerDirectory) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.airlinerDirectory = airlinerDirectory;
        departDate.setMinSelectableDate(new Date(System.currentTimeMillis()));
        departDate.setDate(new Date(System.currentTimeMillis()));
        populateAirlinerList();
    }

    public void populateAirlinerList() {
        ArrayList<Airliner> airlinerList = airlinerDirectory.getAirlinerList();
        for (Airliner eachAirliner : airlinerList) {
            chooseAirliner.addItem(eachAirliner.getAirlinerName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createFlightLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        flightIdField = new javax.swing.JTextField();
        flightNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        createFlightBtn = new javax.swing.JButton();
        createFlightBackBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        chooseAirliner = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        sourceLocField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        destLocField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        departDate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        maxSeatCount = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        departTimeField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pricePerTicket = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createFlightLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createFlightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createFlightLabel.setText("Create new flight in Airliner");
        createFlightLabel.setToolTipText("");
        add(createFlightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 740, 35));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Choose airliner : ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 90, 190, 28));

        flightIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightIdFieldActionPerformed(evt);
            }
        });
        add(flightIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 136, 30));
        add(flightNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 136, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Enter flight name : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 180, 20));

        createFlightBtn.setBackground(new java.awt.Color(0, 153, 153));
        createFlightBtn.setText("Create");
        createFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFlightBtnActionPerformed(evt);
            }
        });
        add(createFlightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 90, -1));

        createFlightBackBtn.setBackground(new java.awt.Color(0, 153, 153));
        createFlightBackBtn.setText("<< Back");
        createFlightBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFlightBackBtnActionPerformed(evt);
            }
        });
        add(createFlightBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Enter flight Id :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 190, 20));

        add(chooseAirliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 140, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Enter Source Location : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 190, 20));

        sourceLocField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceLocFieldActionPerformed(evt);
            }
        });
        add(sourceLocField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 136, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Choose Max seats in the flight :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 190, 20));

        destLocField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destLocFieldActionPerformed(evt);
            }
        });
        add(destLocField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 136, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Enter Destination Location : ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 190, 20));

        departDate.setAutoscrolls(true);
        add(departDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 140, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Enter price per ticket for this flight : ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 230, 20));

        maxSeatCount.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        add(maxSeatCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 140, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Choose departure date : ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 190, 20));

        departTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departTimeFieldActionPerformed(evt);
            }
        });
        add(departTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 136, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Enter departure time : ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 190, 20));

        pricePerTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricePerTicketActionPerformed(evt);
            }
        });
        add(pricePerTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void flightIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightIdFieldActionPerformed

    private void createFlightBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createFlightBackBtnActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        Component[] componentArray = CardSequenceJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        if (!component.getClass().getName().equalsIgnoreCase("UserInterface.ManageAirliners.CreateNewAirlinerJPanel")) {
            ManageFlightsJPanel manageFlightPanel = (ManageFlightsJPanel) component;
            manageFlightPanel.populateManageFlightPanel();
        }
        CardLayout cardLayout = (CardLayout) CardSequenceJPanel.getLayout();
        cardLayout.previous(CardSequenceJPanel);
    }//GEN-LAST:event_createFlightBackBtnActionPerformed

    private void createFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createFlightBtnActionPerformed
        // TODO add your handling code here:
        String flightName = flightNameField.getText();
        String sourceLoc = sourceLocField.getText();
        String destLoc = destLocField.getText();
        Date departureDate = departDate.getDate();

        if (flightIdField.getText().isEmpty() || flightName.isEmpty() || sourceLoc.isEmpty() || destLoc.isEmpty() || pricePerTicket.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All the fields are mandatory!!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Long flightId = Long.parseLong(String.valueOf(flightIdField.getText()));
                float pricePerSeat = Float.parseFloat(String.valueOf(pricePerTicket.getText()));
                String departTime = departTimeField.getText();
                
                String airlinerName = chooseAirliner.getSelectedItem().toString();
                Airliner airliner = airlinerDirectory.getAirlinerByName(airlinerName);
                Flight newFlight = airliner.getFleet().addNewFlight();
                newFlight.setFlightId(flightId);
                newFlight.setFlightName(flightName);
                newFlight.setAirlinerName(airlinerName);
                newFlight.setMaxSeatCount((int) maxSeatCount.getValue());
                newFlight.setSeatAvailable((int) maxSeatCount.getValue());
                newFlight.setPricePerTicket(pricePerSeat);

                Schedule schedule = new Schedule();
                schedule.setSourceLocation(sourceLoc);
                schedule.setDestLocation(destLoc);
                schedule.setDepartureDate(departureDate);
                
                DateFormat timeFormatter = new SimpleDateFormat("HH:mm");
                Date departureTime = timeFormatter.parse(departTime);
                schedule.setDepartureTime(new java.sql.Time(departureTime.getTime()));
                newFlight.setSchedule(schedule);

                JOptionPane.showMessageDialog(null, "Flight successfully added in " + airlinerName + "!");
                resetFields();
            } catch (ParseException ex) {
                Logger.getLogger(CreateNewFlightJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_createFlightBtnActionPerformed

    private void sourceLocFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceLocFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceLocFieldActionPerformed

    private void destLocFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destLocFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destLocFieldActionPerformed

    private void departTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departTimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departTimeFieldActionPerformed

    private void pricePerTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricePerTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricePerTicketActionPerformed
    public void resetFields() {
        flightIdField.setText("");
        flightNameField.setText("");
        sourceLocField.setText("");
        destLocField.setText("");
        departDate.setDate(new Date(System.currentTimeMillis()));
        maxSeatCount.setValue(1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> chooseAirliner;
    private javax.swing.JButton createFlightBackBtn;
    private javax.swing.JButton createFlightBtn;
    private javax.swing.JLabel createFlightLabel;
    private com.toedter.calendar.JDateChooser departDate;
    private javax.swing.JTextField departTimeField;
    private javax.swing.JTextField destLocField;
    private javax.swing.JTextField flightIdField;
    private javax.swing.JTextField flightNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner maxSeatCount;
    private javax.swing.JTextField pricePerTicket;
    private javax.swing.JTextField sourceLocField;
    // End of variables declaration//GEN-END:variables
}
