/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageFlights;

import Business.Airliner;
import Business.Flight;
import Business.AirlinerDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import sun.swing.MenuItemLayoutHelper;

/**
 *
 * @author Menita Koonani
 */
public class ManageFlightsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageFlightsJPanel
     */
    private AirlinerDirectory airlinerDirectory;
    private javax.swing.JPanel CardSequenceJPanel;
    
    public ManageFlightsJPanel(javax.swing.JPanel CardSequenceJPanel, AirlinerDirectory airlinerDirectory) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.airlinerDirectory = airlinerDirectory;
        populateManageFlightPanel();
    }
    
    public void populateManageFlightPanel() {
        populateAirlinerDropdown();
        populateManageFlightsTable();
    }
    
    public void populateAirlinerDropdown() {
        chooseAirlinerDropdown.removeAllItems();
        chooseAirlinerDropdown.addItem("Select");
        ArrayList<Airliner> airlinerList = airlinerDirectory.getAirlinerList();
        for (Airliner eachAirliner : airlinerList) {
            chooseAirlinerDropdown.addItem(eachAirliner.getAirlinerName());
        }
    }
    
    public void populateManageFlightsTable() {
        DefaultTableModel jTable = (DefaultTableModel) manageFlightsTable.getModel();
        //starting the population form row 0
        jTable.setRowCount(0);
        
        for (Airliner eachAirliner : airlinerDirectory.getAirlinerList()) {
            for (Flight eachFlight : eachAirliner.getFleet().getFlightList()) {
                Object row[] = new Object[7];
                //setting the object to the first row as we need to access all the other attributes of that particular object
                row[0] = eachFlight;
                row[1] = eachAirliner;
                row[2] = eachAirliner.getAirlinerName();
                row[3] = eachFlight.getFlightName();
                row[4] = eachFlight.getSchedule().getSourceLocation();
                row[5] = eachFlight.getSchedule().getDestLocation();
                row[6] = eachFlight.getSchedule().getDepartureDate();
                jTable.addRow(row);
            }
        }
    }
    
    public void populateManageFlightsTable(ArrayList<Flight> flightList) {
        DefaultTableModel jTable = (DefaultTableModel) manageFlightsTable.getModel();
        //starting the population form row 0
        jTable.setRowCount(0);
        
        manageFlightsTable.removeColumn(manageFlightsTable.getColumn("Airliner Id"));
        manageFlightsTable.removeColumn(manageFlightsTable.getColumn("Airliner Name"));
        
        for (Flight eachFlight : flightList) {
            Object row[] = new Object[7];
            //setting the object to the first row as we need to access all the other attributes of that particular object
            row[0] = eachFlight;
            row[3] = eachFlight.getFlightName();
            row[4] = eachFlight.getSchedule().getSourceLocation();
            row[5] = eachFlight.getSchedule().getDestLocation();
            row[6] = eachFlight.getSchedule().getDepartureDate();
            jTable.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mangeFlightsLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        chooseAirlinerDropdown = new javax.swing.JComboBox<>();
        listFlightsBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageFlightsTable = new javax.swing.JTable();
        newFlightBtn = new javax.swing.JButton();
        viewFlightBtn = new javax.swing.JButton();
        sourceLocField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        destLocField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mangeFlightsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mangeFlightsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mangeFlightsLabel.setText("Manage Flights");
        mangeFlightsLabel.setToolTipText("");
        add(mangeFlightsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 810, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choose airliner : ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 130, 30));

        chooseAirlinerDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        chooseAirlinerDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseAirlinerDropdownActionPerformed(evt);
            }
        });
        add(chooseAirlinerDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 170, 30));

        listFlightsBtn.setBackground(new java.awt.Color(0, 153, 153));
        listFlightsBtn.setText("List Flights");
        listFlightsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listFlightsBtnActionPerformed(evt);
            }
        });
        add(listFlightsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 90, 30));

        manageFlightsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Id", "Airliner Id", "Airliner Name", "Flight Name", "Source", "Destination", "Departure Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        manageFlightsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(manageFlightsTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 810, 240));

        newFlightBtn.setBackground(new java.awt.Color(0, 153, 153));
        newFlightBtn.setText("New Flight >>");
        newFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFlightBtnActionPerformed(evt);
            }
        });
        add(newFlightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 383, 130, 30));

        viewFlightBtn.setBackground(new java.awt.Color(0, 153, 153));
        viewFlightBtn.setText("View Flight >>");
        viewFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFlightBtnActionPerformed(evt);
            }
        });
        add(viewFlightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 130, 30));
        add(sourceLocField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 170, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter Source Location : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter Destination : ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 140, 30));
        add(destLocField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 170, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void chooseAirlinerDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseAirlinerDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseAirlinerDropdownActionPerformed

    private void listFlightsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listFlightsBtnActionPerformed
        // TODO add your handling code here:
        ArrayList<Flight> flightList = new ArrayList<>();
        String airlinerName = chooseAirlinerDropdown.getSelectedItem().toString();
        if (!airlinerName.equalsIgnoreCase("Select")) {
            Airliner selectedAirliner = airlinerDirectory.getAirlinerByName(airlinerName);
            flightList = selectedAirliner.getFleet().getFlightList();
        } else {
            flightList = airlinerDirectory.getAllFlightsList();
        }
        
        String sourceLoc = sourceLocField.getText();
        if (!sourceLoc.isEmpty()) {
            flightList = airlinerDirectory.getFlightsBySource(sourceLoc, flightList);
        }
        
        String destLoc = destLocField.getText();
        if (!destLoc.isEmpty()) {
            flightList = airlinerDirectory.getFlightsByDestination(destLoc, flightList);
        }
        
        populateManageFlightsTable(flightList);
    }//GEN-LAST:event_listFlightsBtnActionPerformed

    private void newFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFlightBtnActionPerformed
        // TODO add your handling code here:
        CreateNewFlightJPanel newFlightPanel = new CreateNewFlightJPanel(CardSequenceJPanel, airlinerDirectory);
        CardLayout cardLayout = (CardLayout) CardSequenceJPanel.getLayout();
        CardSequenceJPanel.add("NewFlightPanel", newFlightPanel);
        cardLayout.next(CardSequenceJPanel);
    }//GEN-LAST:event_newFlightBtnActionPerformed

    private void viewFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFlightBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = manageFlightsTable.getSelectedRow();
        if (selectedRow >= 0) {
            Flight selectedFlight = (Flight) manageFlightsTable.getValueAt(selectedRow, 0);
            ViewFlightsJPanel viewFlightPanel = new ViewFlightsJPanel(CardSequenceJPanel, selectedFlight);
            CardLayout cardLayout = (CardLayout) CardSequenceJPanel.getLayout();
            CardSequenceJPanel.add("ViewFlightPanel", viewFlightPanel);
            cardLayout.next(CardSequenceJPanel);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_viewFlightBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> chooseAirlinerDropdown;
    private javax.swing.JTextField destLocField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listFlightsBtn;
    private javax.swing.JTable manageFlightsTable;
    private javax.swing.JLabel mangeFlightsLabel;
    private javax.swing.JButton newFlightBtn;
    private javax.swing.JTextField sourceLocField;
    private javax.swing.JButton viewFlightBtn;
    // End of variables declaration//GEN-END:variables
}
