/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageFlights;

import Business.Airliner;
import Business.Flight;
import Business.Schedule;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.crypto.dsig.spec.C14NMethodParameterSpec;

/**
 *
 * @author Menita Koonani
 */
public class ViewFlightsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFlightsJPanel
     */
    private javax.swing.JPanel CardSeqenceJPanel;
    private Flight flight;

    public ViewFlightsJPanel(javax.swing.JPanel CardSequenceJPanel, Flight flight) {
        initComponents();
        this.CardSeqenceJPanel = CardSequenceJPanel;
        this.flight = flight;
        departDate.setMinSelectableDate(new Date(System.currentTimeMillis()));
        populateViewFlight(false);
    }

    public void populateViewFlight(boolean isEditable) {
        isEditable(isEditable);

        viewFlightsLabel.setText("View flight in " + flight.getAirlinerName() + " airlines");
        flightIdField.setText(String.valueOf(flight.getFlightId()));
        flightNameField.setText(flight.getFlightName());
        sourceLocField.setText(flight.getSchedule().getSourceLocation());
        destLocField.setText((flight.getSchedule().getDestLocation()));
        departDate.setDate(flight.getSchedule().getDepartureDate());
        departTimeField.setText(String.valueOf(flight.getSchedule().getDepartureTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewFlightsLabel = new javax.swing.JLabel();
        viewFlightBackBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        flightIdField = new javax.swing.JTextField();
        flightNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cancelUpdateBtn = new javax.swing.JButton();
        updateFlightBtn = new javax.swing.JButton();
        saveFlightBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        sourceLocField = new javax.swing.JTextField();
        destLocField = new javax.swing.JTextField();
        departDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        departTimeField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewFlightsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewFlightsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewFlightsLabel.setText("View Flights in Airliner");
        viewFlightsLabel.setToolTipText("");
        add(viewFlightsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 740, 35));

        viewFlightBackBtn.setBackground(new java.awt.Color(0, 153, 153));
        viewFlightBackBtn.setText("<< Back");
        viewFlightBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFlightBackBtnActionPerformed(evt);
            }
        });
        add(viewFlightBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 90, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Flight ID :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 157, 28));

        flightIdField.setEditable(false);
        flightIdField.setEnabled(false);
        flightIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightIdFieldActionPerformed(evt);
            }
        });
        add(flightIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 136, 32));
        add(flightNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 136, 32));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Flight Name : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 157, 28));

        cancelUpdateBtn.setBackground(new java.awt.Color(0, 153, 153));
        cancelUpdateBtn.setText("Cancel");
        cancelUpdateBtn.setEnabled(false);
        cancelUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelUpdateBtnActionPerformed(evt);
            }
        });
        add(cancelUpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        updateFlightBtn.setBackground(new java.awt.Color(0, 153, 153));
        updateFlightBtn.setText("Update");
        updateFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFlightBtnActionPerformed(evt);
            }
        });
        add(updateFlightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, -1));

        saveFlightBtn.setBackground(new java.awt.Color(0, 153, 153));
        saveFlightBtn.setText("Save");
        saveFlightBtn.setEnabled(false);
        saveFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFlightBtnActionPerformed(evt);
            }
        });
        add(saveFlightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Source Location : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 190, 28));

        sourceLocField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceLocFieldActionPerformed(evt);
            }
        });
        add(sourceLocField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 136, 32));

        destLocField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destLocFieldActionPerformed(evt);
            }
        });
        add(destLocField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 136, 32));

        departDate.setAutoscrolls(true);
        add(departDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 140, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Departure Date : ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 190, 28));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Destination Location : ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 190, 28));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Departure Time : ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 190, 28));

        departTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departTimeFieldActionPerformed(evt);
            }
        });
        add(departTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 136, 32));
    }// </editor-fold>//GEN-END:initComponents

    private void viewFlightBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFlightBackBtnActionPerformed
        // TODO add your handling code here:
        CardSeqenceJPanel.remove(this);
        Component[] componentArray = CardSeqenceJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageFlightsJPanel manageFlightsPanel = (ManageFlightsJPanel) component;
        manageFlightsPanel.populateManageFlightPanel();
        CardLayout cardLayout = (CardLayout) CardSeqenceJPanel.getLayout();
        cardLayout.previous(CardSeqenceJPanel);

    }//GEN-LAST:event_viewFlightBackBtnActionPerformed

    private void flightIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightIdFieldActionPerformed

    private void cancelUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelUpdateBtnActionPerformed
        // TODO add your handling code here:
        populateViewFlight(false);
    }//GEN-LAST:event_cancelUpdateBtnActionPerformed

    private void updateFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFlightBtnActionPerformed
        // TODO add your handling code here:
        isEditable(true);
    }//GEN-LAST:event_updateFlightBtnActionPerformed

    private void saveFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFlightBtnActionPerformed
        // TODO add your handling code here:
        String flightName = flightNameField.getText();
        String sourceLoc = sourceLocField.getText();
        String destLoc = destLocField.getText();
        Date departureDate = departDate.getDate();
        String departTime = departTimeField.getText();

        if (flightName.isEmpty() || sourceLoc.isEmpty() || destLoc.isEmpty() || departTime.isEmpty()) {
            JOptionPane.showMessageDialog(null, "All the fields are mandatory!!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                flight.setFlightName(flightName);
                Schedule schedule = new Schedule();
                schedule.setSourceLocation(sourceLoc);
                schedule.setDestLocation(destLoc);
                schedule.setDepartureDate(departureDate);
                
                DateFormat timeFormatter = new SimpleDateFormat("HH:mm");
                Date departureTime = timeFormatter.parse(departTime);
                schedule.setDepartureTime(new java.sql.Time(departureTime.getTime()));
                
                flight.setSchedule(schedule);
                JOptionPane.showMessageDialog(null, "Flight updated successfully!!");
                isEditable(false);
            } catch (ParseException ex) {
                Logger.getLogger(ViewFlightsJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_saveFlightBtnActionPerformed

    private void sourceLocFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceLocFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceLocFieldActionPerformed

    private void destLocFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destLocFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destLocFieldActionPerformed

    private void departTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departTimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departTimeFieldActionPerformed

    public void isEditable(boolean isEditable) {
        saveFlightBtn.setEnabled(isEditable);
        cancelUpdateBtn.setEnabled(isEditable);
        updateFlightBtn.setEnabled(!isEditable);
        flightNameField.setEditable(isEditable);
        sourceLocField.setEditable(isEditable);
        destLocField.setEditable(isEditable);
        departDate.setEnabled(isEditable);
        departTimeField.setEditable(isEditable);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelUpdateBtn;
    private com.toedter.calendar.JDateChooser departDate;
    private javax.swing.JTextField departTimeField;
    private javax.swing.JTextField destLocField;
    private javax.swing.JTextField flightIdField;
    private javax.swing.JTextField flightNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton saveFlightBtn;
    private javax.swing.JTextField sourceLocField;
    private javax.swing.JButton updateFlightBtn;
    private javax.swing.JButton viewFlightBackBtn;
    private javax.swing.JLabel viewFlightsLabel;
    // End of variables declaration//GEN-END:variables
}
