/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomers;

import Business.Customer;
import Business.CustomerDirectory;
import Business.Flight;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Menita Koonani
 */
public class BookFlightPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookFlightPanel
     */
    private javax.swing.JPanel CardSequenceJPanel;
    private Flight flight;
    private TravelAgency travelAgency;

    public BookFlightPanel(javax.swing.JPanel CardSequenceJPanel, Flight flight, TravelAgency travelAgency) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.flight = flight;
        this.travelAgency = travelAgency;
        totalCostValue.setVisible(false);
        totalCostLabel.setVisible(false);
        confirmBookingBtn.setVisible(false);
        dobField.setMaxSelectableDate(new Date(System.currentTimeMillis()));
        SpinnerNumberModel spinnerModel = (SpinnerNumberModel) numSeats.getModel();
        spinnerModel.setMaximum(flight.getSeatAvailable());

        populateBookFlightPanel();
    }

    public void populateBookFlightPanel() {
        try {
            airlinerName.setText(flight.getAirlinerName());
            flightId.setText(String.valueOf(flight.getFlightId()));
            flightName.setText(flight.getFlightName());
            fromLocation.setText(flight.getSchedule().getSourceLocation());
            toLocation.setText(flight.getSchedule().getDestLocation());
            ticketPrice.setText(String.valueOf(flight.getPricePerTicket()));
            String departureDate = String.valueOf(flight.getSchedule().getDepartureDate());
            SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
            departDate.setText(dateFormat.format(dateFormat.parse(departureDate)));
            departDate.setText(String.valueOf(flight.getSchedule().getDepartureDate()));
        } catch (ParseException ex) {
            Logger.getLogger(BookFlightPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ticketPrice = new javax.swing.JLabel();
        flightId = new javax.swing.JLabel();
        flightName = new javax.swing.JLabel();
        fromLocation = new javax.swing.JLabel();
        airlinerName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        dobField = new com.toedter.calendar.JDateChooser();
        bookFlightBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        toLocation = new javax.swing.JLabel();
        bookFlightBackBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        numSeats = new javax.swing.JSpinner();
        totalCostLabel = new javax.swing.JLabel();
        confirmBookingBtn = new javax.swing.JButton();
        totalCostValue = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        departDate = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 750, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Date of Birth : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 130, 20));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Airliner Name : ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 100, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Flight Name : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 70, 20));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("From : ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 70, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("To : ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 70, 20));
        add(ticketPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 120, 20));
        add(flightId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 120, 20));
        add(flightName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 120, 20));
        add(fromLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 120, 20));
        add(airlinerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 120, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Book Flight");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 750, 40));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Per Ticket Price : ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 110, 20));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Choose number of Seats : ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 150, 20));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Enter Last Name : ");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 130, 20));
        add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 120, -1));
        add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 120, -1));
        add(dobField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 120, -1));

        bookFlightBtn.setBackground(new java.awt.Color(0, 153, 153));
        bookFlightBtn.setText("Book Flight");
        bookFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFlightBtnActionPerformed(evt);
            }
        });
        add(bookFlightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 100, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Flight ID : ");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 70, 20));
        add(toLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 120, 20));

        bookFlightBackBtn.setBackground(new java.awt.Color(0, 153, 153));
        bookFlightBackBtn.setText("<< Back");
        bookFlightBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFlightBackBtnActionPerformed(evt);
            }
        });
        add(bookFlightBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Enter First Name : ");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 130, 20));

        numSeats.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        numSeats.setRequestFocusEnabled(false);
        add(numSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 80, -1));

        totalCostLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalCostLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalCostLabel.setText("Total Cost of Tickets  :");
        add(totalCostLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 150, 40));

        confirmBookingBtn.setBackground(new java.awt.Color(0, 153, 153));
        confirmBookingBtn.setText("Confirm Booking");
        confirmBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBookingBtnActionPerformed(evt);
            }
        });
        add(confirmBookingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 200, -1));

        totalCostValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalCostValue.setForeground(new java.awt.Color(204, 0, 0));
        add(totalCostValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 110, 20));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Departure Date : ");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 130, 20));
        add(departDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 120, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void bookFlightBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFlightBackBtnActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        Component[] componentArray = CardSequenceJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SearchFlightJPanel searchFlightPanel = (SearchFlightJPanel) component;
        searchFlightPanel.populateSearchFlightTable(travelAgency.getAirlinerDirectory().getAvailableFlights(travelAgency.getAllFlights()));
        CardLayout cardLayout = (CardLayout) CardSequenceJPanel.getLayout();
        cardLayout.previous(CardSequenceJPanel);
    }//GEN-LAST:event_bookFlightBackBtnActionPerformed

    private void bookFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFlightBtnActionPerformed
        // TODO add your handling code here:
        String firstName = firstNameField.getText();
        String lastName = lastNameField.getText();
        Date dob = dobField.getDate();
        int totalSeats = (int) numSeats.getValue();
        if (firstName.isEmpty() || lastName.isEmpty() || totalSeats <= 0) {
            JOptionPane.showMessageDialog(null, "All fields are mandatory!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            CustomerDirectory custDir = travelAgency.getCustomerDirectory();
            Customer newCust = custDir.addNewCustomer();
            newCust.setFirstName(firstName);
            newCust.setLastName(lastName);
            newCust.setDateOfBirth(dob);
            newCust.setAirplaneName(airlinerName.getText());
            newCust.setTotalSeatsBooked(totalSeats);

            bookFlightBtn.setEnabled(false);
            firstNameField.setEditable(false);
            lastNameField.setEditable(false);
            dobField.setEnabled(false);
            numSeats.setEnabled(false);

            totalCostValue.setVisible(true);
            totalCostLabel.setVisible(true);
//            float priceFlight = travelAgency.getPriceOfFlight(Long.parseLong(flightId.getText()), airlinerName.getText());
            totalCostLabel.setText("Cost of " + totalSeats + " tickets : USD ");
            float eachCustPrice = Float.parseFloat(ticketPrice.getText()) * totalSeats;
            totalCostValue.setText(String.valueOf(eachCustPrice));
            newCust.setTicketsPrice(eachCustPrice);
            confirmBookingBtn.setVisible(true);
        }

    }//GEN-LAST:event_bookFlightBtnActionPerformed

    private void confirmBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBookingBtnActionPerformed
        // TODO add your handling code here:
        int seatsBooked = (int) numSeats.getValue();
        flight.setSeatAvailable((flight.getSeatAvailable() - seatsBooked));
        JOptionPane.showMessageDialog(null, "Booking confirmed! Have a nice flight!! :D ");
    }//GEN-LAST:event_confirmBookingBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airlinerName;
    private javax.swing.JButton bookFlightBackBtn;
    private javax.swing.JButton bookFlightBtn;
    private javax.swing.JButton confirmBookingBtn;
    private javax.swing.JLabel departDate;
    private com.toedter.calendar.JDateChooser dobField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel flightId;
    private javax.swing.JLabel flightName;
    private javax.swing.JLabel fromLocation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JSpinner numSeats;
    private javax.swing.JLabel ticketPrice;
    private javax.swing.JLabel toLocation;
    private javax.swing.JLabel totalCostLabel;
    private javax.swing.JLabel totalCostValue;
    // End of variables declaration//GEN-END:variables
}
