/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomers;

import Business.Customer;
import Business.Flight;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Menita Koonani
 */
public class ManageBookingsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageBookingsJPanel
     */
    private javax.swing.JPanel CardSequenceJPanel;
    private TravelAgency travelAgency;

    public ManageBookingsJPanel(javax.swing.JPanel CardSequenceJPanel, TravelAgency travelAgency) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.travelAgency = travelAgency;
        populateCustomerTable();
    }

    public void populateCustomerTable() {
        DefaultTableModel jTable = (DefaultTableModel) manageBookingTable.getModel();
        jTable.setRowCount(0);

        for (Customer eachCustomer : travelAgency.getCustomerDirectory().getCustomerList()) {
            Object row[] = new Object[6];
            row[0] = eachCustomer;
            row[1] = eachCustomer.getLastName();
            row[2] = eachCustomer.getTotalSeatsBooked();

            jTable.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewAirlinerLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageBookingTable = new javax.swing.JTable();
        cancelBookingBtn = new javax.swing.JButton();
        manageBookingBackBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewAirlinerLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewAirlinerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewAirlinerLabel.setText("Manage Bookings");
        viewAirlinerLabel.setToolTipText("");
        add(viewAirlinerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 750, 35));

        manageBookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Seats Booked"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageBookingTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 730, 140));

        cancelBookingBtn.setBackground(new java.awt.Color(204, 0, 0));
        cancelBookingBtn.setText("Cancel Booking");
        cancelBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBookingBtnActionPerformed(evt);
            }
        });
        add(cancelBookingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 220, -1));

        manageBookingBackBtn.setBackground(new java.awt.Color(0, 153, 153));
        manageBookingBackBtn.setText("<< Back");
        manageBookingBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBookingBackBtnActionPerformed(evt);
            }
        });
        add(manageBookingBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBookingBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = manageBookingTable.getSelectedRow();
        if (selectedRow >= 0) {
            Customer selectedCustomer = (Customer) manageBookingTable.getValueAt(selectedRow, 0);
            Flight flight = travelAgency.getAirlinerDirectory().getFlightByAirlinerNFlightName(selectedCustomer.getAirlinerName(), selectedCustomer.getAirplaneName());
            flight.setSeatAvailable((flight.getSeatAvailable() + selectedCustomer.getTotalSeatsBooked()));
            travelAgency.getCustomerDirectory().removeCustomer(selectedCustomer);
            JOptionPane.showMessageDialog(null, "Booking cancelled! ");
            populateCustomerTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row! ", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_cancelBookingBtnActionPerformed

    private void manageBookingBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBookingBackBtnActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        Component[] componentArray = CardSequenceJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SearchFlightJPanel searchFlightPanel = (SearchFlightJPanel) component;
        searchFlightPanel.populateSearchFlightTable(travelAgency.getAirlinerDirectory().getAvailableFlights(travelAgency.getAllFlights()));
        CardLayout cardLayout = (CardLayout) CardSequenceJPanel.getLayout();
        cardLayout.previous(CardSequenceJPanel);
    }//GEN-LAST:event_manageBookingBackBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBookingBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageBookingBackBtn;
    private javax.swing.JTable manageBookingTable;
    private javax.swing.JLabel viewAirlinerLabel;
    // End of variables declaration//GEN-END:variables
}
